# Autogenerated from syscall_64.tbl
# Generated by tools/gen_linux_sl.py
# Linux syscall constants + convenience wrappers for L2

# File descriptor constants
macro fd_stdin 0 0 ;
macro fd_stdout 0 1 ;
macro fd_stderr 0 2 ;

# Common open(2) flags
macro O_RDONLY 0 0 ;
macro O_WRONLY 0 1 ;
macro O_RDWR 0 2 ;
macro O_CREAT 0 64 ;
macro O_EXCL 0 128 ;
macro O_NOCTTY 0 256 ;
macro O_TRUNC 0 512 ;
macro O_APPEND 0 1024 ;
macro O_NONBLOCK 0 2048 ;
macro O_CLOEXEC 0 524288 ;

# lseek(2)
macro SEEK_SET 0 0 ;
macro SEEK_CUR 0 1 ;
macro SEEK_END 0 2 ;

# mmap(2)
macro PROT_NONE 0 0 ;
macro PROT_READ 0 1 ;
macro PROT_WRITE 0 2 ;
macro PROT_EXEC 0 4 ;
macro MAP_PRIVATE 0 2 ;
macro MAP_ANONYMOUS 0 32 ;
macro MAP_SHARED 0 1 ;

# Socket constants
macro AF_UNIX 0 1 ;
macro AF_INET 0 2 ;
macro AF_INET6 0 10 ;
macro SOCK_STREAM 0 1 ;
macro SOCK_DGRAM 0 2 ;
macro SOCK_NONBLOCK 0 2048 ;
macro SOCK_CLOEXEC 0 524288 ;

macro INADDR_ANY 0 0 ;

# Generic syscall helpers with explicit argument count
# Stack form:
#   syscall  -> <argN> ... <arg0> <argc> <nr> syscall
#   syscallN -> <argN-1> ... <arg0> <nr> syscallN

# swap impl is provided so this can be used without stdlib
# ___linux_swap [*, x1 | x2] -> [*, x2 | x1]
:asm ___linux_swap {
    mov rax, [r12]
    mov rbx, [r12 + 8]
    mov [r12], rbx
    mov [r12 + 8], rax
}
;

macro syscall0 0
    0
    ___linux_swap
    syscall
;

macro syscall1 0
    1
    ___linux_swap
    syscall
;

macro syscall2 0
    2
    ___linux_swap
    syscall
;

macro syscall3 0
    3
    ___linux_swap
    syscall
;

macro syscall4 0
    4
    ___linux_swap
    syscall
;

macro syscall5 0
    5
    ___linux_swap
    syscall
;

macro syscall6 0
    6
    ___linux_swap
    syscall
;

macro syscall.read 0
    0
    syscall3
;

macro syscall.read.num 0
    0
;

macro syscall.read.argc 0
    3
;

macro syscall.write 0
    1
    syscall3
;

macro syscall.write.num 0
    1
;

macro syscall.write.argc 0
    3
;

macro syscall.open 0
    2
    syscall3
;

macro syscall.open.num 0
    2
;

macro syscall.open.argc 0
    3
;

macro syscall.close 0
    3
    syscall1
;

macro syscall.close.num 0
    3
;

macro syscall.close.argc 0
    1
;

macro syscall.stat 0
    4
    syscall2
;

macro syscall.stat.num 0
    4
;

macro syscall.stat.argc 0
    2
;

macro syscall.newstat 0
    4
    syscall2
;

macro syscall.newstat.num 0
    4
;

macro syscall.newstat.argc 0
    2
;

macro syscall.fstat 0
    5
    syscall2
;

macro syscall.fstat.num 0
    5
;

macro syscall.fstat.argc 0
    2
;

macro syscall.newfstat 0
    5
    syscall2
;

macro syscall.newfstat.num 0
    5
;

macro syscall.newfstat.argc 0
    2
;

macro syscall.lstat 0
    6
    syscall2
;

macro syscall.lstat.num 0
    6
;

macro syscall.lstat.argc 0
    2
;

macro syscall.newlstat 0
    6
    syscall2
;

macro syscall.newlstat.num 0
    6
;

macro syscall.newlstat.argc 0
    2
;

macro syscall.poll 0
    7
    syscall3
;

macro syscall.poll.num 0
    7
;

macro syscall.poll.argc 0
    3
;

macro syscall.lseek 0
    8
    syscall3
;

macro syscall.lseek.num 0
    8
;

macro syscall.lseek.argc 0
    3
;

macro syscall.mmap 0
    9
    syscall6
;

macro syscall.mmap.num 0
    9
;

macro syscall.mmap.argc 0
    6
;

macro syscall.mprotect 0
    10
    syscall3
;

macro syscall.mprotect.num 0
    10
;

macro syscall.mprotect.argc 0
    3
;

macro syscall.munmap 0
    11
    syscall2
;

macro syscall.munmap.num 0
    11
;

macro syscall.munmap.argc 0
    2
;

macro syscall.brk 0
    12
    syscall1
;

macro syscall.brk.num 0
    12
;

macro syscall.brk.argc 0
    1
;

macro syscall.rt_sigaction 0
    13
    syscall4
;

macro syscall.rt_sigaction.num 0
    13
;

macro syscall.rt_sigaction.argc 0
    4
;

macro syscall.rt_sigprocmask 0
    14
    syscall4
;

macro syscall.rt_sigprocmask.num 0
    14
;

macro syscall.rt_sigprocmask.argc 0
    4
;

macro syscall.rt_sigreturn 0
    15
    syscall0
;

macro syscall.rt_sigreturn.num 0
    15
;

macro syscall.rt_sigreturn.argc 0
    0
;

macro syscall.ioctl 0
    16
    syscall3
;

macro syscall.ioctl.num 0
    16
;

macro syscall.ioctl.argc 0
    3
;

macro syscall.pread64 0
    17
    syscall4
;

macro syscall.pread64.num 0
    17
;

macro syscall.pread64.argc 0
    4
;

macro syscall.pwrite64 0
    18
    syscall4
;

macro syscall.pwrite64.num 0
    18
;

macro syscall.pwrite64.argc 0
    4
;

macro syscall.readv 0
    19
    syscall3
;

macro syscall.readv.num 0
    19
;

macro syscall.readv.argc 0
    3
;

macro syscall.writev 0
    20
    syscall3
;

macro syscall.writev.num 0
    20
;

macro syscall.writev.argc 0
    3
;

macro syscall.access 0
    21
    syscall2
;

macro syscall.access.num 0
    21
;

macro syscall.access.argc 0
    2
;

macro syscall.pipe 0
    22
    syscall1
;

macro syscall.pipe.num 0
    22
;

macro syscall.pipe.argc 0
    1
;

macro syscall.select 0
    23
    syscall5
;

macro syscall.select.num 0
    23
;

macro syscall.select.argc 0
    5
;

macro syscall.sched_yield 0
    24
    syscall0
;

macro syscall.sched_yield.num 0
    24
;

macro syscall.sched_yield.argc 0
    0
;

macro syscall.mremap 0
    25
    syscall5
;

macro syscall.mremap.num 0
    25
;

macro syscall.mremap.argc 0
    5
;

macro syscall.msync 0
    26
    syscall3
;

macro syscall.msync.num 0
    26
;

macro syscall.msync.argc 0
    3
;

macro syscall.mincore 0
    27
    syscall3
;

macro syscall.mincore.num 0
    27
;

macro syscall.mincore.argc 0
    3
;

macro syscall.madvise 0
    28
    syscall3
;

macro syscall.madvise.num 0
    28
;

macro syscall.madvise.argc 0
    3
;

macro syscall.shmget 0
    29
    syscall3
;

macro syscall.shmget.num 0
    29
;

macro syscall.shmget.argc 0
    3
;

macro syscall.shmat 0
    30
    syscall3
;

macro syscall.shmat.num 0
    30
;

macro syscall.shmat.argc 0
    3
;

macro syscall.shmctl 0
    31
    syscall3
;

macro syscall.shmctl.num 0
    31
;

macro syscall.shmctl.argc 0
    3
;

macro syscall.dup 0
    32
    syscall1
;

macro syscall.dup.num 0
    32
;

macro syscall.dup.argc 0
    1
;

macro syscall.dup2 0
    33
    syscall2
;

macro syscall.dup2.num 0
    33
;

macro syscall.dup2.argc 0
    2
;

macro syscall.pause 0
    34
    syscall0
;

macro syscall.pause.num 0
    34
;

macro syscall.pause.argc 0
    0
;

macro syscall.nanosleep 0
    35
    syscall2
;

macro syscall.nanosleep.num 0
    35
;

macro syscall.nanosleep.argc 0
    2
;

macro syscall.getitimer 0
    36
    syscall2
;

macro syscall.getitimer.num 0
    36
;

macro syscall.getitimer.argc 0
    2
;

macro syscall.alarm 0
    37
    syscall1
;

macro syscall.alarm.num 0
    37
;

macro syscall.alarm.argc 0
    1
;

macro syscall.setitimer 0
    38
    syscall3
;

macro syscall.setitimer.num 0
    38
;

macro syscall.setitimer.argc 0
    3
;

macro syscall.getpid 0
    39
    syscall0
;

macro syscall.getpid.num 0
    39
;

macro syscall.getpid.argc 0
    0
;

macro syscall.sendfile 0
    40
    syscall4
;

macro syscall.sendfile.num 0
    40
;

macro syscall.sendfile.argc 0
    4
;

macro syscall.sendfile64 0
    40
    syscall4
;

macro syscall.sendfile64.num 0
    40
;

macro syscall.sendfile64.argc 0
    4
;

macro syscall.socket 0
    41
    syscall3
;

macro syscall.socket.num 0
    41
;

macro syscall.socket.argc 0
    3
;

macro syscall.connect 0
    42
    syscall3
;

macro syscall.connect.num 0
    42
;

macro syscall.connect.argc 0
    3
;

macro syscall.accept 0
    43
    syscall3
;

macro syscall.accept.num 0
    43
;

macro syscall.accept.argc 0
    3
;

macro syscall.sendto 0
    44
    syscall6
;

macro syscall.sendto.num 0
    44
;

macro syscall.sendto.argc 0
    6
;

macro syscall.recvfrom 0
    45
    syscall6
;

macro syscall.recvfrom.num 0
    45
;

macro syscall.recvfrom.argc 0
    6
;

macro syscall.sendmsg 0
    46
    syscall3
;

macro syscall.sendmsg.num 0
    46
;

macro syscall.sendmsg.argc 0
    3
;

macro syscall.recvmsg 0
    47
    syscall3
;

macro syscall.recvmsg.num 0
    47
;

macro syscall.recvmsg.argc 0
    3
;

macro syscall.shutdown 0
    48
    syscall2
;

macro syscall.shutdown.num 0
    48
;

macro syscall.shutdown.argc 0
    2
;

macro syscall.bind 0
    49
    syscall3
;

macro syscall.bind.num 0
    49
;

macro syscall.bind.argc 0
    3
;

macro syscall.listen 0
    50
    syscall2
;

macro syscall.listen.num 0
    50
;

macro syscall.listen.argc 0
    2
;

macro syscall.getsockname 0
    51
    syscall3
;

macro syscall.getsockname.num 0
    51
;

macro syscall.getsockname.argc 0
    3
;

macro syscall.getpeername 0
    52
    syscall3
;

macro syscall.getpeername.num 0
    52
;

macro syscall.getpeername.argc 0
    3
;

macro syscall.socketpair 0
    53
    syscall4
;

macro syscall.socketpair.num 0
    53
;

macro syscall.socketpair.argc 0
    4
;

macro syscall.setsockopt 0
    54
    syscall5
;

macro syscall.setsockopt.num 0
    54
;

macro syscall.setsockopt.argc 0
    5
;

macro syscall.getsockopt 0
    55
    syscall5
;

macro syscall.getsockopt.num 0
    55
;

macro syscall.getsockopt.argc 0
    5
;

macro syscall.clone 0
    56
    syscall5
;

macro syscall.clone.num 0
    56
;

macro syscall.clone.argc 0
    5
;

macro syscall.fork 0
    57
    syscall0
;

macro syscall.fork.num 0
    57
;

macro syscall.fork.argc 0
    0
;

macro syscall.vfork 0
    58
    syscall0
;

macro syscall.vfork.num 0
    58
;

macro syscall.vfork.argc 0
    0
;

macro syscall.execve 0
    59
    syscall3
;

macro syscall.execve.num 0
    59
;

macro syscall.execve.argc 0
    3
;

macro syscall.exit 0
    60
    syscall1
;

macro syscall.exit.num 0
    60
;

macro syscall.exit.argc 0
    1
;

macro syscall.wait4 0
    61
    syscall4
;

macro syscall.wait4.num 0
    61
;

macro syscall.wait4.argc 0
    4
;

macro syscall.kill 0
    62
    syscall2
;

macro syscall.kill.num 0
    62
;

macro syscall.kill.argc 0
    2
;

macro syscall.uname 0
    63
    syscall1
;

macro syscall.uname.num 0
    63
;

macro syscall.uname.argc 0
    1
;

macro syscall.newuname 0
    63
    syscall1
;

macro syscall.newuname.num 0
    63
;

macro syscall.newuname.argc 0
    1
;

macro syscall.semget 0
    64
    syscall3
;

macro syscall.semget.num 0
    64
;

macro syscall.semget.argc 0
    3
;

macro syscall.semop 0
    65
    syscall3
;

macro syscall.semop.num 0
    65
;

macro syscall.semop.argc 0
    3
;

macro syscall.semctl 0
    66
    syscall4
;

macro syscall.semctl.num 0
    66
;

macro syscall.semctl.argc 0
    4
;

macro syscall.shmdt 0
    67
    syscall1
;

macro syscall.shmdt.num 0
    67
;

macro syscall.shmdt.argc 0
    1
;

macro syscall.msgget 0
    68
    syscall2
;

macro syscall.msgget.num 0
    68
;

macro syscall.msgget.argc 0
    2
;

macro syscall.msgsnd 0
    69
    syscall4
;

macro syscall.msgsnd.num 0
    69
;

macro syscall.msgsnd.argc 0
    4
;

macro syscall.msgrcv 0
    70
    syscall5
;

macro syscall.msgrcv.num 0
    70
;

macro syscall.msgrcv.argc 0
    5
;

macro syscall.msgctl 0
    71
    syscall3
;

macro syscall.msgctl.num 0
    71
;

macro syscall.msgctl.argc 0
    3
;

macro syscall.fcntl 0
    72
    syscall3
;

macro syscall.fcntl.num 0
    72
;

macro syscall.fcntl.argc 0
    3
;

macro syscall.flock 0
    73
    syscall2
;

macro syscall.flock.num 0
    73
;

macro syscall.flock.argc 0
    2
;

macro syscall.fsync 0
    74
    syscall1
;

macro syscall.fsync.num 0
    74
;

macro syscall.fsync.argc 0
    1
;

macro syscall.fdatasync 0
    75
    syscall1
;

macro syscall.fdatasync.num 0
    75
;

macro syscall.fdatasync.argc 0
    1
;

macro syscall.truncate 0
    76
    syscall2
;

macro syscall.truncate.num 0
    76
;

macro syscall.truncate.argc 0
    2
;

macro syscall.ftruncate 0
    77
    syscall2
;

macro syscall.ftruncate.num 0
    77
;

macro syscall.ftruncate.argc 0
    2
;

macro syscall.getdents 0
    78
    syscall3
;

macro syscall.getdents.num 0
    78
;

macro syscall.getdents.argc 0
    3
;

macro syscall.getcwd 0
    79
    syscall2
;

macro syscall.getcwd.num 0
    79
;

macro syscall.getcwd.argc 0
    2
;

macro syscall.chdir 0
    80
    syscall1
;

macro syscall.chdir.num 0
    80
;

macro syscall.chdir.argc 0
    1
;

macro syscall.fchdir 0
    81
    syscall1
;

macro syscall.fchdir.num 0
    81
;

macro syscall.fchdir.argc 0
    1
;

macro syscall.rename 0
    82
    syscall2
;

macro syscall.rename.num 0
    82
;

macro syscall.rename.argc 0
    2
;

macro syscall.mkdir 0
    83
    syscall2
;

macro syscall.mkdir.num 0
    83
;

macro syscall.mkdir.argc 0
    2
;

macro syscall.rmdir 0
    84
    syscall1
;

macro syscall.rmdir.num 0
    84
;

macro syscall.rmdir.argc 0
    1
;

macro syscall.creat 0
    85
    syscall2
;

macro syscall.creat.num 0
    85
;

macro syscall.creat.argc 0
    2
;

macro syscall.link 0
    86
    syscall2
;

macro syscall.link.num 0
    86
;

macro syscall.link.argc 0
    2
;

macro syscall.unlink 0
    87
    syscall1
;

macro syscall.unlink.num 0
    87
;

macro syscall.unlink.argc 0
    1
;

macro syscall.symlink 0
    88
    syscall2
;

macro syscall.symlink.num 0
    88
;

macro syscall.symlink.argc 0
    2
;

macro syscall.readlink 0
    89
    syscall3
;

macro syscall.readlink.num 0
    89
;

macro syscall.readlink.argc 0
    3
;

macro syscall.chmod 0
    90
    syscall2
;

macro syscall.chmod.num 0
    90
;

macro syscall.chmod.argc 0
    2
;

macro syscall.fchmod 0
    91
    syscall2
;

macro syscall.fchmod.num 0
    91
;

macro syscall.fchmod.argc 0
    2
;

macro syscall.chown 0
    92
    syscall3
;

macro syscall.chown.num 0
    92
;

macro syscall.chown.argc 0
    3
;

macro syscall.fchown 0
    93
    syscall3
;

macro syscall.fchown.num 0
    93
;

macro syscall.fchown.argc 0
    3
;

macro syscall.lchown 0
    94
    syscall3
;

macro syscall.lchown.num 0
    94
;

macro syscall.lchown.argc 0
    3
;

macro syscall.umask 0
    95
    syscall1
;

macro syscall.umask.num 0
    95
;

macro syscall.umask.argc 0
    1
;

macro syscall.gettimeofday 0
    96
    syscall2
;

macro syscall.gettimeofday.num 0
    96
;

macro syscall.gettimeofday.argc 0
    2
;

macro syscall.getrlimit 0
    97
    syscall2
;

macro syscall.getrlimit.num 0
    97
;

macro syscall.getrlimit.argc 0
    2
;

macro syscall.getrusage 0
    98
    syscall2
;

macro syscall.getrusage.num 0
    98
;

macro syscall.getrusage.argc 0
    2
;

macro syscall.sysinfo 0
    99
    syscall1
;

macro syscall.sysinfo.num 0
    99
;

macro syscall.sysinfo.argc 0
    1
;

macro syscall.times 0
    100
    syscall1
;

macro syscall.times.num 0
    100
;

macro syscall.times.argc 0
    1
;

macro syscall.ptrace 0
    101
    syscall4
;

macro syscall.ptrace.num 0
    101
;

macro syscall.ptrace.argc 0
    4
;

macro syscall.getuid 0
    102
    syscall0
;

macro syscall.getuid.num 0
    102
;

macro syscall.getuid.argc 0
    0
;

macro syscall.syslog 0
    103
    syscall3
;

macro syscall.syslog.num 0
    103
;

macro syscall.syslog.argc 0
    3
;

macro syscall.getgid 0
    104
    syscall0
;

macro syscall.getgid.num 0
    104
;

macro syscall.getgid.argc 0
    0
;

macro syscall.setuid 0
    105
    syscall1
;

macro syscall.setuid.num 0
    105
;

macro syscall.setuid.argc 0
    1
;

macro syscall.setgid 0
    106
    syscall1
;

macro syscall.setgid.num 0
    106
;

macro syscall.setgid.argc 0
    1
;

macro syscall.geteuid 0
    107
    syscall0
;

macro syscall.geteuid.num 0
    107
;

macro syscall.geteuid.argc 0
    0
;

macro syscall.getegid 0
    108
    syscall0
;

macro syscall.getegid.num 0
    108
;

macro syscall.getegid.argc 0
    0
;

macro syscall.setpgid 0
    109
    syscall2
;

macro syscall.setpgid.num 0
    109
;

macro syscall.setpgid.argc 0
    2
;

macro syscall.getppid 0
    110
    syscall0
;

macro syscall.getppid.num 0
    110
;

macro syscall.getppid.argc 0
    0
;

macro syscall.getpgrp 0
    111
    syscall0
;

macro syscall.getpgrp.num 0
    111
;

macro syscall.getpgrp.argc 0
    0
;

macro syscall.setsid 0
    112
    syscall0
;

macro syscall.setsid.num 0
    112
;

macro syscall.setsid.argc 0
    0
;

macro syscall.setreuid 0
    113
    syscall2
;

macro syscall.setreuid.num 0
    113
;

macro syscall.setreuid.argc 0
    2
;

macro syscall.setregid 0
    114
    syscall2
;

macro syscall.setregid.num 0
    114
;

macro syscall.setregid.argc 0
    2
;

macro syscall.getgroups 0
    115
    syscall2
;

macro syscall.getgroups.num 0
    115
;

macro syscall.getgroups.argc 0
    2
;

macro syscall.setgroups 0
    116
    syscall2
;

macro syscall.setgroups.num 0
    116
;

macro syscall.setgroups.argc 0
    2
;

macro syscall.setresuid 0
    117
    syscall3
;

macro syscall.setresuid.num 0
    117
;

macro syscall.setresuid.argc 0
    3
;

macro syscall.getresuid 0
    118
    syscall3
;

macro syscall.getresuid.num 0
    118
;

macro syscall.getresuid.argc 0
    3
;

macro syscall.setresgid 0
    119
    syscall3
;

macro syscall.setresgid.num 0
    119
;

macro syscall.setresgid.argc 0
    3
;

macro syscall.getresgid 0
    120
    syscall3
;

macro syscall.getresgid.num 0
    120
;

macro syscall.getresgid.argc 0
    3
;

macro syscall.getpgid 0
    121
    syscall1
;

macro syscall.getpgid.num 0
    121
;

macro syscall.getpgid.argc 0
    1
;

macro syscall.setfsuid 0
    122
    syscall1
;

macro syscall.setfsuid.num 0
    122
;

macro syscall.setfsuid.argc 0
    1
;

macro syscall.setfsgid 0
    123
    syscall1
;

macro syscall.setfsgid.num 0
    123
;

macro syscall.setfsgid.argc 0
    1
;

macro syscall.getsid 0
    124
    syscall1
;

macro syscall.getsid.num 0
    124
;

macro syscall.getsid.argc 0
    1
;

macro syscall.capget 0
    125
    syscall2
;

macro syscall.capget.num 0
    125
;

macro syscall.capget.argc 0
    2
;

macro syscall.capset 0
    126
    syscall2
;

macro syscall.capset.num 0
    126
;

macro syscall.capset.argc 0
    2
;

macro syscall.rt_sigpending 0
    127
    syscall2
;

macro syscall.rt_sigpending.num 0
    127
;

macro syscall.rt_sigpending.argc 0
    2
;

macro syscall.rt_sigtimedwait 0
    128
    syscall4
;

macro syscall.rt_sigtimedwait.num 0
    128
;

macro syscall.rt_sigtimedwait.argc 0
    4
;

macro syscall.rt_sigqueueinfo 0
    129
    syscall3
;

macro syscall.rt_sigqueueinfo.num 0
    129
;

macro syscall.rt_sigqueueinfo.argc 0
    3
;

macro syscall.rt_sigsuspend 0
    130
    syscall2
;

macro syscall.rt_sigsuspend.num 0
    130
;

macro syscall.rt_sigsuspend.argc 0
    2
;

macro syscall.sigaltstack 0
    131
    syscall2
;

macro syscall.sigaltstack.num 0
    131
;

macro syscall.sigaltstack.argc 0
    2
;

macro syscall.utime 0
    132
    syscall2
;

macro syscall.utime.num 0
    132
;

macro syscall.utime.argc 0
    2
;

macro syscall.mknod 0
    133
    syscall3
;

macro syscall.mknod.num 0
    133
;

macro syscall.mknod.argc 0
    3
;

macro syscall.uselib 0
    134
    syscall1
;

macro syscall.uselib.num 0
    134
;

macro syscall.uselib.argc 0
    1
;

macro syscall.personality 0
    135
    syscall1
;

macro syscall.personality.num 0
    135
;

macro syscall.personality.argc 0
    1
;

macro syscall.ustat 0
    136
    syscall2
;

macro syscall.ustat.num 0
    136
;

macro syscall.ustat.argc 0
    2
;

macro syscall.statfs 0
    137
    syscall2
;

macro syscall.statfs.num 0
    137
;

macro syscall.statfs.argc 0
    2
;

macro syscall.fstatfs 0
    138
    syscall2
;

macro syscall.fstatfs.num 0
    138
;

macro syscall.fstatfs.argc 0
    2
;

macro syscall.sysfs 0
    139
    syscall3
;

macro syscall.sysfs.num 0
    139
;

macro syscall.sysfs.argc 0
    3
;

macro syscall.getpriority 0
    140
    syscall2
;

macro syscall.getpriority.num 0
    140
;

macro syscall.getpriority.argc 0
    2
;

macro syscall.setpriority 0
    141
    syscall3
;

macro syscall.setpriority.num 0
    141
;

macro syscall.setpriority.argc 0
    3
;

macro syscall.sched_setparam 0
    142
    syscall2
;

macro syscall.sched_setparam.num 0
    142
;

macro syscall.sched_setparam.argc 0
    2
;

macro syscall.sched_getparam 0
    143
    syscall2
;

macro syscall.sched_getparam.num 0
    143
;

macro syscall.sched_getparam.argc 0
    2
;

macro syscall.sched_setscheduler 0
    144
    syscall3
;

macro syscall.sched_setscheduler.num 0
    144
;

macro syscall.sched_setscheduler.argc 0
    3
;

macro syscall.sched_getscheduler 0
    145
    syscall1
;

macro syscall.sched_getscheduler.num 0
    145
;

macro syscall.sched_getscheduler.argc 0
    1
;

macro syscall.sched_get_priority_max 0
    146
    syscall1
;

macro syscall.sched_get_priority_max.num 0
    146
;

macro syscall.sched_get_priority_max.argc 0
    1
;

macro syscall.sched_get_priority_min 0
    147
    syscall1
;

macro syscall.sched_get_priority_min.num 0
    147
;

macro syscall.sched_get_priority_min.argc 0
    1
;

macro syscall.sched_rr_get_interval 0
    148
    syscall2
;

macro syscall.sched_rr_get_interval.num 0
    148
;

macro syscall.sched_rr_get_interval.argc 0
    2
;

macro syscall.mlock 0
    149
    syscall2
;

macro syscall.mlock.num 0
    149
;

macro syscall.mlock.argc 0
    2
;

macro syscall.munlock 0
    150
    syscall2
;

macro syscall.munlock.num 0
    150
;

macro syscall.munlock.argc 0
    2
;

macro syscall.mlockall 0
    151
    syscall1
;

macro syscall.mlockall.num 0
    151
;

macro syscall.mlockall.argc 0
    1
;

macro syscall.munlockall 0
    152
    syscall0
;

macro syscall.munlockall.num 0
    152
;

macro syscall.munlockall.argc 0
    0
;

macro syscall.vhangup 0
    153
    syscall0
;

macro syscall.vhangup.num 0
    153
;

macro syscall.vhangup.argc 0
    0
;

macro syscall.modify_ldt 0
    154
    syscall3
;

macro syscall.modify_ldt.num 0
    154
;

macro syscall.modify_ldt.argc 0
    3
;

macro syscall.pivot_root 0
    155
    syscall2
;

macro syscall.pivot_root.num 0
    155
;

macro syscall.pivot_root.argc 0
    2
;

macro syscall.sysctl 0
    156
    syscall1
;

macro syscall.sysctl.num 0
    156
;

macro syscall.sysctl.argc 0
    1
;

macro syscall.ni_syscall 0
    156
    syscall1
;

macro syscall.ni_syscall.num 0
    156
;

macro syscall.ni_syscall.argc 0
    1
;

macro syscall.prctl 0
    157
    syscall5
;

macro syscall.prctl.num 0
    157
;

macro syscall.prctl.argc 0
    5
;

macro syscall.arch_prctl 0
    158
    syscall2
;

macro syscall.arch_prctl.num 0
    158
;

macro syscall.arch_prctl.argc 0
    2
;

macro syscall.adjtimex 0
    159
    syscall1
;

macro syscall.adjtimex.num 0
    159
;

macro syscall.adjtimex.argc 0
    1
;

macro syscall.setrlimit 0
    160
    syscall2
;

macro syscall.setrlimit.num 0
    160
;

macro syscall.setrlimit.argc 0
    2
;

macro syscall.chroot 0
    161
    syscall1
;

macro syscall.chroot.num 0
    161
;

macro syscall.chroot.argc 0
    1
;

macro syscall.sync 0
    162
    syscall0
;

macro syscall.sync.num 0
    162
;

macro syscall.sync.argc 0
    0
;

macro syscall.acct 0
    163
    syscall1
;

macro syscall.acct.num 0
    163
;

macro syscall.acct.argc 0
    1
;

macro syscall.settimeofday 0
    164
    syscall2
;

macro syscall.settimeofday.num 0
    164
;

macro syscall.settimeofday.argc 0
    2
;

macro syscall.mount 0
    165
    syscall5
;

macro syscall.mount.num 0
    165
;

macro syscall.mount.argc 0
    5
;

macro syscall.umount2 0
    166
    syscall2
;

macro syscall.umount2.num 0
    166
;

macro syscall.umount2.argc 0
    2
;

macro syscall.umount 0
    166
    syscall2
;

macro syscall.umount.num 0
    166
;

macro syscall.umount.argc 0
    2
;

macro syscall.swapon 0
    167
    syscall2
;

macro syscall.swapon.num 0
    167
;

macro syscall.swapon.argc 0
    2
;

macro syscall.swapoff 0
    168
    syscall1
;

macro syscall.swapoff.num 0
    168
;

macro syscall.swapoff.argc 0
    1
;

macro syscall.reboot 0
    169
    syscall4
;

macro syscall.reboot.num 0
    169
;

macro syscall.reboot.argc 0
    4
;

macro syscall.sethostname 0
    170
    syscall2
;

macro syscall.sethostname.num 0
    170
;

macro syscall.sethostname.argc 0
    2
;

macro syscall.setdomainname 0
    171
    syscall2
;

macro syscall.setdomainname.num 0
    171
;

macro syscall.setdomainname.argc 0
    2
;

macro syscall.iopl 0
    172
    syscall1
;

macro syscall.iopl.num 0
    172
;

macro syscall.iopl.argc 0
    1
;

macro syscall.ioperm 0
    173
    syscall3
;

macro syscall.ioperm.num 0
    173
;

macro syscall.ioperm.argc 0
    3
;

macro syscall.create_module 0
    174
    syscall2
;

macro syscall.create_module.num 0
    174
;

macro syscall.create_module.argc 0
    2
;

macro syscall.init_module 0
    175
    syscall3
;

macro syscall.init_module.num 0
    175
;

macro syscall.init_module.argc 0
    3
;

macro syscall.delete_module 0
    176
    syscall2
;

macro syscall.delete_module.num 0
    176
;

macro syscall.delete_module.argc 0
    2
;

macro syscall.get_kernel_syms 0
    177
    syscall1
;

macro syscall.get_kernel_syms.num 0
    177
;

macro syscall.get_kernel_syms.argc 0
    1
;

macro syscall.query_module 0
    178
    syscall5
;

macro syscall.query_module.num 0
    178
;

macro syscall.query_module.argc 0
    5
;

macro syscall.quotactl 0
    179
    syscall4
;

macro syscall.quotactl.num 0
    179
;

macro syscall.quotactl.argc 0
    4
;

macro syscall.nfsservctl 0
    180
    syscall3
;

macro syscall.nfsservctl.num 0
    180
;

macro syscall.nfsservctl.argc 0
    3
;

macro syscall.getpmsg 0
    181
    syscall5
;

macro syscall.getpmsg.num 0
    181
;

macro syscall.getpmsg.argc 0
    5
;

macro syscall.putpmsg 0
    182
    syscall5
;

macro syscall.putpmsg.num 0
    182
;

macro syscall.putpmsg.argc 0
    5
;

macro syscall.afs_syscall 0
    183
    syscall5
;

macro syscall.afs_syscall.num 0
    183
;

macro syscall.afs_syscall.argc 0
    5
;

macro syscall.tuxcall 0
    184
    syscall3
;

macro syscall.tuxcall.num 0
    184
;

macro syscall.tuxcall.argc 0
    3
;

macro syscall.security 0
    185
    syscall3
;

macro syscall.security.num 0
    185
;

macro syscall.security.argc 0
    3
;

macro syscall.gettid 0
    186
    syscall0
;

macro syscall.gettid.num 0
    186
;

macro syscall.gettid.argc 0
    0
;

macro syscall.readahead 0
    187
    syscall3
;

macro syscall.readahead.num 0
    187
;

macro syscall.readahead.argc 0
    3
;

macro syscall.setxattr 0
    188
    syscall5
;

macro syscall.setxattr.num 0
    188
;

macro syscall.setxattr.argc 0
    5
;

macro syscall.lsetxattr 0
    189
    syscall5
;

macro syscall.lsetxattr.num 0
    189
;

macro syscall.lsetxattr.argc 0
    5
;

macro syscall.fsetxattr 0
    190
    syscall5
;

macro syscall.fsetxattr.num 0
    190
;

macro syscall.fsetxattr.argc 0
    5
;

macro syscall.getxattr 0
    191
    syscall4
;

macro syscall.getxattr.num 0
    191
;

macro syscall.getxattr.argc 0
    4
;

macro syscall.lgetxattr 0
    192
    syscall4
;

macro syscall.lgetxattr.num 0
    192
;

macro syscall.lgetxattr.argc 0
    4
;

macro syscall.fgetxattr 0
    193
    syscall4
;

macro syscall.fgetxattr.num 0
    193
;

macro syscall.fgetxattr.argc 0
    4
;

macro syscall.listxattr 0
    194
    syscall3
;

macro syscall.listxattr.num 0
    194
;

macro syscall.listxattr.argc 0
    3
;

macro syscall.llistxattr 0
    195
    syscall3
;

macro syscall.llistxattr.num 0
    195
;

macro syscall.llistxattr.argc 0
    3
;

macro syscall.flistxattr 0
    196
    syscall3
;

macro syscall.flistxattr.num 0
    196
;

macro syscall.flistxattr.argc 0
    3
;

macro syscall.removexattr 0
    197
    syscall2
;

macro syscall.removexattr.num 0
    197
;

macro syscall.removexattr.argc 0
    2
;

macro syscall.lremovexattr 0
    198
    syscall2
;

macro syscall.lremovexattr.num 0
    198
;

macro syscall.lremovexattr.argc 0
    2
;

macro syscall.fremovexattr 0
    199
    syscall2
;

macro syscall.fremovexattr.num 0
    199
;

macro syscall.fremovexattr.argc 0
    2
;

macro syscall.tkill 0
    200
    syscall2
;

macro syscall.tkill.num 0
    200
;

macro syscall.tkill.argc 0
    2
;

macro syscall.time 0
    201
    syscall1
;

macro syscall.time.num 0
    201
;

macro syscall.time.argc 0
    1
;

macro syscall.futex 0
    202
    syscall6
;

macro syscall.futex.num 0
    202
;

macro syscall.futex.argc 0
    6
;

macro syscall.sched_setaffinity 0
    203
    syscall3
;

macro syscall.sched_setaffinity.num 0
    203
;

macro syscall.sched_setaffinity.argc 0
    3
;

macro syscall.sched_getaffinity 0
    204
    syscall3
;

macro syscall.sched_getaffinity.num 0
    204
;

macro syscall.sched_getaffinity.argc 0
    3
;

macro syscall.set_thread_area 0
    205
    syscall1
;

macro syscall.set_thread_area.num 0
    205
;

macro syscall.set_thread_area.argc 0
    1
;

macro syscall.io_setup 0
    206
    syscall2
;

macro syscall.io_setup.num 0
    206
;

macro syscall.io_setup.argc 0
    2
;

macro syscall.io_destroy 0
    207
    syscall1
;

macro syscall.io_destroy.num 0
    207
;

macro syscall.io_destroy.argc 0
    1
;

macro syscall.io_getevents 0
    208
    syscall5
;

macro syscall.io_getevents.num 0
    208
;

macro syscall.io_getevents.argc 0
    5
;

macro syscall.io_submit 0
    209
    syscall3
;

macro syscall.io_submit.num 0
    209
;

macro syscall.io_submit.argc 0
    3
;

macro syscall.io_cancel 0
    210
    syscall3
;

macro syscall.io_cancel.num 0
    210
;

macro syscall.io_cancel.argc 0
    3
;

macro syscall.get_thread_area 0
    211
    syscall1
;

macro syscall.get_thread_area.num 0
    211
;

macro syscall.get_thread_area.argc 0
    1
;

macro syscall.lookup_dcookie 0
    212
    syscall3
;

macro syscall.lookup_dcookie.num 0
    212
;

macro syscall.lookup_dcookie.argc 0
    3
;

macro syscall.epoll_create 0
    213
    syscall1
;

macro syscall.epoll_create.num 0
    213
;

macro syscall.epoll_create.argc 0
    1
;

macro syscall.epoll_ctl_old 0
    214
    syscall4
;

macro syscall.epoll_ctl_old.num 0
    214
;

macro syscall.epoll_ctl_old.argc 0
    4
;

macro syscall.epoll_wait_old 0
    215
    syscall4
;

macro syscall.epoll_wait_old.num 0
    215
;

macro syscall.epoll_wait_old.argc 0
    4
;

macro syscall.remap_file_pages 0
    216
    syscall5
;

macro syscall.remap_file_pages.num 0
    216
;

macro syscall.remap_file_pages.argc 0
    5
;

macro syscall.getdents64 0
    217
    syscall3
;

macro syscall.getdents64.num 0
    217
;

macro syscall.getdents64.argc 0
    3
;

macro syscall.set_tid_address 0
    218
    syscall1
;

macro syscall.set_tid_address.num 0
    218
;

macro syscall.set_tid_address.argc 0
    1
;

macro syscall.restart_syscall 0
    219
    syscall0
;

macro syscall.restart_syscall.num 0
    219
;

macro syscall.restart_syscall.argc 0
    0
;

macro syscall.semtimedop 0
    220
    syscall4
;

macro syscall.semtimedop.num 0
    220
;

macro syscall.semtimedop.argc 0
    4
;

macro syscall.fadvise64 0
    221
    syscall4
;

macro syscall.fadvise64.num 0
    221
;

macro syscall.fadvise64.argc 0
    4
;

macro syscall.timer_create 0
    222
    syscall3
;

macro syscall.timer_create.num 0
    222
;

macro syscall.timer_create.argc 0
    3
;

macro syscall.timer_settime 0
    223
    syscall4
;

macro syscall.timer_settime.num 0
    223
;

macro syscall.timer_settime.argc 0
    4
;

macro syscall.timer_gettime 0
    224
    syscall2
;

macro syscall.timer_gettime.num 0
    224
;

macro syscall.timer_gettime.argc 0
    2
;

macro syscall.timer_getoverrun 0
    225
    syscall1
;

macro syscall.timer_getoverrun.num 0
    225
;

macro syscall.timer_getoverrun.argc 0
    1
;

macro syscall.timer_delete 0
    226
    syscall1
;

macro syscall.timer_delete.num 0
    226
;

macro syscall.timer_delete.argc 0
    1
;

macro syscall.clock_settime 0
    227
    syscall2
;

macro syscall.clock_settime.num 0
    227
;

macro syscall.clock_settime.argc 0
    2
;

macro syscall.clock_gettime 0
    228
    syscall2
;

macro syscall.clock_gettime.num 0
    228
;

macro syscall.clock_gettime.argc 0
    2
;

macro syscall.clock_getres 0
    229
    syscall2
;

macro syscall.clock_getres.num 0
    229
;

macro syscall.clock_getres.argc 0
    2
;

macro syscall.clock_nanosleep 0
    230
    syscall4
;

macro syscall.clock_nanosleep.num 0
    230
;

macro syscall.clock_nanosleep.argc 0
    4
;

macro syscall.exit_group 0
    231
    syscall1
;

macro syscall.exit_group.num 0
    231
;

macro syscall.exit_group.argc 0
    1
;

macro syscall.epoll_wait 0
    232
    syscall4
;

macro syscall.epoll_wait.num 0
    232
;

macro syscall.epoll_wait.argc 0
    4
;

macro syscall.epoll_ctl 0
    233
    syscall4
;

macro syscall.epoll_ctl.num 0
    233
;

macro syscall.epoll_ctl.argc 0
    4
;

macro syscall.tgkill 0
    234
    syscall3
;

macro syscall.tgkill.num 0
    234
;

macro syscall.tgkill.argc 0
    3
;

macro syscall.utimes 0
    235
    syscall2
;

macro syscall.utimes.num 0
    235
;

macro syscall.utimes.argc 0
    2
;

macro syscall.vserver 0
    236
    syscall5
;

macro syscall.vserver.num 0
    236
;

macro syscall.vserver.argc 0
    5
;

macro syscall.mbind 0
    237
    syscall6
;

macro syscall.mbind.num 0
    237
;

macro syscall.mbind.argc 0
    6
;

macro syscall.set_mempolicy 0
    238
    syscall3
;

macro syscall.set_mempolicy.num 0
    238
;

macro syscall.set_mempolicy.argc 0
    3
;

macro syscall.get_mempolicy 0
    239
    syscall5
;

macro syscall.get_mempolicy.num 0
    239
;

macro syscall.get_mempolicy.argc 0
    5
;

macro syscall.mq_open 0
    240
    syscall4
;

macro syscall.mq_open.num 0
    240
;

macro syscall.mq_open.argc 0
    4
;

macro syscall.mq_unlink 0
    241
    syscall1
;

macro syscall.mq_unlink.num 0
    241
;

macro syscall.mq_unlink.argc 0
    1
;

macro syscall.mq_timedsend 0
    242
    syscall5
;

macro syscall.mq_timedsend.num 0
    242
;

macro syscall.mq_timedsend.argc 0
    5
;

macro syscall.mq_timedreceive 0
    243
    syscall5
;

macro syscall.mq_timedreceive.num 0
    243
;

macro syscall.mq_timedreceive.argc 0
    5
;

macro syscall.mq_notify 0
    244
    syscall2
;

macro syscall.mq_notify.num 0
    244
;

macro syscall.mq_notify.argc 0
    2
;

macro syscall.mq_getsetattr 0
    245
    syscall3
;

macro syscall.mq_getsetattr.num 0
    245
;

macro syscall.mq_getsetattr.argc 0
    3
;

macro syscall.kexec_load 0
    246
    syscall4
;

macro syscall.kexec_load.num 0
    246
;

macro syscall.kexec_load.argc 0
    4
;

macro syscall.waitid 0
    247
    syscall5
;

macro syscall.waitid.num 0
    247
;

macro syscall.waitid.argc 0
    5
;

macro syscall.add_key 0
    248
    syscall5
;

macro syscall.add_key.num 0
    248
;

macro syscall.add_key.argc 0
    5
;

macro syscall.request_key 0
    249
    syscall4
;

macro syscall.request_key.num 0
    249
;

macro syscall.request_key.argc 0
    4
;

macro syscall.keyctl 0
    250
    syscall5
;

macro syscall.keyctl.num 0
    250
;

macro syscall.keyctl.argc 0
    5
;

macro syscall.ioprio_set 0
    251
    syscall3
;

macro syscall.ioprio_set.num 0
    251
;

macro syscall.ioprio_set.argc 0
    3
;

macro syscall.ioprio_get 0
    252
    syscall2
;

macro syscall.ioprio_get.num 0
    252
;

macro syscall.ioprio_get.argc 0
    2
;

macro syscall.inotify_init 0
    253
    syscall0
;

macro syscall.inotify_init.num 0
    253
;

macro syscall.inotify_init.argc 0
    0
;

macro syscall.inotify_add_watch 0
    254
    syscall3
;

macro syscall.inotify_add_watch.num 0
    254
;

macro syscall.inotify_add_watch.argc 0
    3
;

macro syscall.inotify_rm_watch 0
    255
    syscall2
;

macro syscall.inotify_rm_watch.num 0
    255
;

macro syscall.inotify_rm_watch.argc 0
    2
;

macro syscall.migrate_pages 0
    256
    syscall4
;

macro syscall.migrate_pages.num 0
    256
;

macro syscall.migrate_pages.argc 0
    4
;

macro syscall.openat 0
    257
    syscall4
;

macro syscall.openat.num 0
    257
;

macro syscall.openat.argc 0
    4
;

macro syscall.mkdirat 0
    258
    syscall3
;

macro syscall.mkdirat.num 0
    258
;

macro syscall.mkdirat.argc 0
    3
;

macro syscall.mknodat 0
    259
    syscall4
;

macro syscall.mknodat.num 0
    259
;

macro syscall.mknodat.argc 0
    4
;

macro syscall.fchownat 0
    260
    syscall5
;

macro syscall.fchownat.num 0
    260
;

macro syscall.fchownat.argc 0
    5
;

macro syscall.futimesat 0
    261
    syscall3
;

macro syscall.futimesat.num 0
    261
;

macro syscall.futimesat.argc 0
    3
;

macro syscall.newfstatat 0
    262
    syscall4
;

macro syscall.newfstatat.num 0
    262
;

macro syscall.newfstatat.argc 0
    4
;

macro syscall.unlinkat 0
    263
    syscall3
;

macro syscall.unlinkat.num 0
    263
;

macro syscall.unlinkat.argc 0
    3
;

macro syscall.renameat 0
    264
    syscall4
;

macro syscall.renameat.num 0
    264
;

macro syscall.renameat.argc 0
    4
;

macro syscall.linkat 0
    265
    syscall5
;

macro syscall.linkat.num 0
    265
;

macro syscall.linkat.argc 0
    5
;

macro syscall.symlinkat 0
    266
    syscall3
;

macro syscall.symlinkat.num 0
    266
;

macro syscall.symlinkat.argc 0
    3
;

macro syscall.readlinkat 0
    267
    syscall4
;

macro syscall.readlinkat.num 0
    267
;

macro syscall.readlinkat.argc 0
    4
;

macro syscall.fchmodat 0
    268
    syscall3
;

macro syscall.fchmodat.num 0
    268
;

macro syscall.fchmodat.argc 0
    3
;

macro syscall.faccessat 0
    269
    syscall3
;

macro syscall.faccessat.num 0
    269
;

macro syscall.faccessat.argc 0
    3
;

macro syscall.pselect6 0
    270
    syscall6
;

macro syscall.pselect6.num 0
    270
;

macro syscall.pselect6.argc 0
    6
;

macro syscall.ppoll 0
    271
    syscall5
;

macro syscall.ppoll.num 0
    271
;

macro syscall.ppoll.argc 0
    5
;

macro syscall.unshare 0
    272
    syscall1
;

macro syscall.unshare.num 0
    272
;

macro syscall.unshare.argc 0
    1
;

macro syscall.set_robust_list 0
    273
    syscall2
;

macro syscall.set_robust_list.num 0
    273
;

macro syscall.set_robust_list.argc 0
    2
;

macro syscall.get_robust_list 0
    274
    syscall3
;

macro syscall.get_robust_list.num 0
    274
;

macro syscall.get_robust_list.argc 0
    3
;

macro syscall.splice 0
    275
    syscall6
;

macro syscall.splice.num 0
    275
;

macro syscall.splice.argc 0
    6
;

macro syscall.tee 0
    276
    syscall4
;

macro syscall.tee.num 0
    276
;

macro syscall.tee.argc 0
    4
;

macro syscall.sync_file_range 0
    277
    syscall4
;

macro syscall.sync_file_range.num 0
    277
;

macro syscall.sync_file_range.argc 0
    4
;

macro syscall.vmsplice 0
    278
    syscall4
;

macro syscall.vmsplice.num 0
    278
;

macro syscall.vmsplice.argc 0
    4
;

macro syscall.move_pages 0
    279
    syscall6
;

macro syscall.move_pages.num 0
    279
;

macro syscall.move_pages.argc 0
    6
;

macro syscall.utimensat 0
    280
    syscall4
;

macro syscall.utimensat.num 0
    280
;

macro syscall.utimensat.argc 0
    4
;

macro syscall.epoll_pwait 0
    281
    syscall6
;

macro syscall.epoll_pwait.num 0
    281
;

macro syscall.epoll_pwait.argc 0
    6
;

macro syscall.signalfd 0
    282
    syscall3
;

macro syscall.signalfd.num 0
    282
;

macro syscall.signalfd.argc 0
    3
;

macro syscall.timerfd_create 0
    283
    syscall2
;

macro syscall.timerfd_create.num 0
    283
;

macro syscall.timerfd_create.argc 0
    2
;

macro syscall.eventfd 0
    284
    syscall1
;

macro syscall.eventfd.num 0
    284
;

macro syscall.eventfd.argc 0
    1
;

macro syscall.fallocate 0
    285
    syscall4
;

macro syscall.fallocate.num 0
    285
;

macro syscall.fallocate.argc 0
    4
;

macro syscall.timerfd_settime 0
    286
    syscall4
;

macro syscall.timerfd_settime.num 0
    286
;

macro syscall.timerfd_settime.argc 0
    4
;

macro syscall.timerfd_gettime 0
    287
    syscall2
;

macro syscall.timerfd_gettime.num 0
    287
;

macro syscall.timerfd_gettime.argc 0
    2
;

macro syscall.accept4 0
    288
    syscall4
;

macro syscall.accept4.num 0
    288
;

macro syscall.accept4.argc 0
    4
;

macro syscall.signalfd4 0
    289
    syscall4
;

macro syscall.signalfd4.num 0
    289
;

macro syscall.signalfd4.argc 0
    4
;

macro syscall.eventfd2 0
    290
    syscall2
;

macro syscall.eventfd2.num 0
    290
;

macro syscall.eventfd2.argc 0
    2
;

macro syscall.epoll_create1 0
    291
    syscall1
;

macro syscall.epoll_create1.num 0
    291
;

macro syscall.epoll_create1.argc 0
    1
;

macro syscall.dup3 0
    292
    syscall3
;

macro syscall.dup3.num 0
    292
;

macro syscall.dup3.argc 0
    3
;

macro syscall.pipe2 0
    293
    syscall2
;

macro syscall.pipe2.num 0
    293
;

macro syscall.pipe2.argc 0
    2
;

macro syscall.inotify_init1 0
    294
    syscall1
;

macro syscall.inotify_init1.num 0
    294
;

macro syscall.inotify_init1.argc 0
    1
;

macro syscall.preadv 0
    295
    syscall4
;

macro syscall.preadv.num 0
    295
;

macro syscall.preadv.argc 0
    4
;

macro syscall.pwritev 0
    296
    syscall4
;

macro syscall.pwritev.num 0
    296
;

macro syscall.pwritev.argc 0
    4
;

macro syscall.rt_tgsigqueueinfo 0
    297
    syscall4
;

macro syscall.rt_tgsigqueueinfo.num 0
    297
;

macro syscall.rt_tgsigqueueinfo.argc 0
    4
;

macro syscall.perf_event_open 0
    298
    syscall5
;

macro syscall.perf_event_open.num 0
    298
;

macro syscall.perf_event_open.argc 0
    5
;

macro syscall.recvmmsg 0
    299
    syscall5
;

macro syscall.recvmmsg.num 0
    299
;

macro syscall.recvmmsg.argc 0
    5
;

macro syscall.fanotify_init 0
    300
    syscall2
;

macro syscall.fanotify_init.num 0
    300
;

macro syscall.fanotify_init.argc 0
    2
;

macro syscall.fanotify_mark 0
    301
    syscall5
;

macro syscall.fanotify_mark.num 0
    301
;

macro syscall.fanotify_mark.argc 0
    5
;

macro syscall.prlimit64 0
    302
    syscall4
;

macro syscall.prlimit64.num 0
    302
;

macro syscall.prlimit64.argc 0
    4
;

macro syscall.name_to_handle_at 0
    303
    syscall5
;

macro syscall.name_to_handle_at.num 0
    303
;

macro syscall.name_to_handle_at.argc 0
    5
;

macro syscall.open_by_handle_at 0
    304
    syscall3
;

macro syscall.open_by_handle_at.num 0
    304
;

macro syscall.open_by_handle_at.argc 0
    3
;

macro syscall.clock_adjtime 0
    305
    syscall2
;

macro syscall.clock_adjtime.num 0
    305
;

macro syscall.clock_adjtime.argc 0
    2
;

macro syscall.syncfs 0
    306
    syscall1
;

macro syscall.syncfs.num 0
    306
;

macro syscall.syncfs.argc 0
    1
;

macro syscall.sendmmsg 0
    307
    syscall4
;

macro syscall.sendmmsg.num 0
    307
;

macro syscall.sendmmsg.argc 0
    4
;

macro syscall.setns 0
    308
    syscall2
;

macro syscall.setns.num 0
    308
;

macro syscall.setns.argc 0
    2
;

macro syscall.getcpu 0
    309
    syscall3
;

macro syscall.getcpu.num 0
    309
;

macro syscall.getcpu.argc 0
    3
;

macro syscall.process_vm_readv 0
    310
    syscall6
;

macro syscall.process_vm_readv.num 0
    310
;

macro syscall.process_vm_readv.argc 0
    6
;

macro syscall.process_vm_writev 0
    311
    syscall6
;

macro syscall.process_vm_writev.num 0
    311
;

macro syscall.process_vm_writev.argc 0
    6
;

macro syscall.kcmp 0
    312
    syscall5
;

macro syscall.kcmp.num 0
    312
;

macro syscall.kcmp.argc 0
    5
;

macro syscall.finit_module 0
    313
    syscall3
;

macro syscall.finit_module.num 0
    313
;

macro syscall.finit_module.argc 0
    3
;

macro syscall.sched_setattr 0
    314
    syscall3
;

macro syscall.sched_setattr.num 0
    314
;

macro syscall.sched_setattr.argc 0
    3
;

macro syscall.sched_getattr 0
    315
    syscall4
;

macro syscall.sched_getattr.num 0
    315
;

macro syscall.sched_getattr.argc 0
    4
;

macro syscall.renameat2 0
    316
    syscall5
;

macro syscall.renameat2.num 0
    316
;

macro syscall.renameat2.argc 0
    5
;

macro syscall.seccomp 0
    317
    syscall3
;

macro syscall.seccomp.num 0
    317
;

macro syscall.seccomp.argc 0
    3
;

macro syscall.getrandom 0
    318
    syscall3
;

macro syscall.getrandom.num 0
    318
;

macro syscall.getrandom.argc 0
    3
;

macro syscall.memfd_create 0
    319
    syscall2
;

macro syscall.memfd_create.num 0
    319
;

macro syscall.memfd_create.argc 0
    2
;

macro syscall.kexec_file_load 0
    320
    syscall5
;

macro syscall.kexec_file_load.num 0
    320
;

macro syscall.kexec_file_load.argc 0
    5
;

macro syscall.bpf 0
    321
    syscall3
;

macro syscall.bpf.num 0
    321
;

macro syscall.bpf.argc 0
    3
;

macro syscall.execveat 0
    322
    syscall5
;

macro syscall.execveat.num 0
    322
;

macro syscall.execveat.argc 0
    5
;

macro syscall.userfaultfd 0
    323
    syscall1
;

macro syscall.userfaultfd.num 0
    323
;

macro syscall.userfaultfd.argc 0
    1
;

macro syscall.membarrier 0
    324
    syscall3
;

macro syscall.membarrier.num 0
    324
;

macro syscall.membarrier.argc 0
    3
;

macro syscall.mlock2 0
    325
    syscall3
;

macro syscall.mlock2.num 0
    325
;

macro syscall.mlock2.argc 0
    3
;

macro syscall.copy_file_range 0
    326
    syscall6
;

macro syscall.copy_file_range.num 0
    326
;

macro syscall.copy_file_range.argc 0
    6
;

macro syscall.preadv2 0
    327
    syscall6
;

macro syscall.preadv2.num 0
    327
;

macro syscall.preadv2.argc 0
    6
;

macro syscall.pwritev2 0
    328
    syscall6
;

macro syscall.pwritev2.num 0
    328
;

macro syscall.pwritev2.argc 0
    6
;

macro syscall.pkey_mprotect 0
    329
    syscall4
;

macro syscall.pkey_mprotect.num 0
    329
;

macro syscall.pkey_mprotect.argc 0
    4
;

macro syscall.pkey_alloc 0
    330
    syscall2
;

macro syscall.pkey_alloc.num 0
    330
;

macro syscall.pkey_alloc.argc 0
    2
;

macro syscall.pkey_free 0
    331
    syscall1
;

macro syscall.pkey_free.num 0
    331
;

macro syscall.pkey_free.argc 0
    1
;

macro syscall.statx 0
    332
    syscall5
;

macro syscall.statx.num 0
    332
;

macro syscall.statx.argc 0
    5
;

macro syscall.io_pgetevents 0
    333
    syscall6
;

macro syscall.io_pgetevents.num 0
    333
;

macro syscall.io_pgetevents.argc 0
    6
;

macro syscall.rseq 0
    334
    syscall4
;

macro syscall.rseq.num 0
    334
;

macro syscall.rseq.argc 0
    4
;

macro syscall.uretprobe 0
    335
    syscall0
;

macro syscall.uretprobe.num 0
    335
;

macro syscall.uretprobe.argc 0
    0
;

macro syscall.uprobe 0
    336
    syscall0
;

macro syscall.uprobe.num 0
    336
;

macro syscall.uprobe.argc 0
    0
;

macro syscall.pidfd_send_signal 0
    424
    syscall0
;

macro syscall.pidfd_send_signal.num 0
    424
;

macro syscall.pidfd_send_signal.argc 0
    0
;

macro syscall.io_uring_setup 0
    425
    syscall0
;

macro syscall.io_uring_setup.num 0
    425
;

macro syscall.io_uring_setup.argc 0
    0
;

macro syscall.io_uring_enter 0
    426
    syscall0
;

macro syscall.io_uring_enter.num 0
    426
;

macro syscall.io_uring_enter.argc 0
    0
;

macro syscall.io_uring_register 0
    427
    syscall0
;

macro syscall.io_uring_register.num 0
    427
;

macro syscall.io_uring_register.argc 0
    0
;

macro syscall.open_tree 0
    428
    syscall0
;

macro syscall.open_tree.num 0
    428
;

macro syscall.open_tree.argc 0
    0
;

macro syscall.move_mount 0
    429
    syscall0
;

macro syscall.move_mount.num 0
    429
;

macro syscall.move_mount.argc 0
    0
;

macro syscall.fsopen 0
    430
    syscall0
;

macro syscall.fsopen.num 0
    430
;

macro syscall.fsopen.argc 0
    0
;

macro syscall.fsconfig 0
    431
    syscall0
;

macro syscall.fsconfig.num 0
    431
;

macro syscall.fsconfig.argc 0
    0
;

macro syscall.fsmount 0
    432
    syscall0
;

macro syscall.fsmount.num 0
    432
;

macro syscall.fsmount.argc 0
    0
;

macro syscall.fspick 0
    433
    syscall0
;

macro syscall.fspick.num 0
    433
;

macro syscall.fspick.argc 0
    0
;

macro syscall.pidfd_open 0
    434
    syscall0
;

macro syscall.pidfd_open.num 0
    434
;

macro syscall.pidfd_open.argc 0
    0
;

macro syscall.clone3 0
    435
    syscall0
;

macro syscall.clone3.num 0
    435
;

macro syscall.clone3.argc 0
    0
;

macro syscall.close_range 0
    436
    syscall0
;

macro syscall.close_range.num 0
    436
;

macro syscall.close_range.argc 0
    0
;

macro syscall.openat2 0
    437
    syscall0
;

macro syscall.openat2.num 0
    437
;

macro syscall.openat2.argc 0
    0
;

macro syscall.pidfd_getfd 0
    438
    syscall0
;

macro syscall.pidfd_getfd.num 0
    438
;

macro syscall.pidfd_getfd.argc 0
    0
;

macro syscall.faccessat2 0
    439
    syscall0
;

macro syscall.faccessat2.num 0
    439
;

macro syscall.faccessat2.argc 0
    0
;

macro syscall.process_madvise 0
    440
    syscall0
;

macro syscall.process_madvise.num 0
    440
;

macro syscall.process_madvise.argc 0
    0
;

macro syscall.epoll_pwait2 0
    441
    syscall0
;

macro syscall.epoll_pwait2.num 0
    441
;

macro syscall.epoll_pwait2.argc 0
    0
;

macro syscall.mount_setattr 0
    442
    syscall0
;

macro syscall.mount_setattr.num 0
    442
;

macro syscall.mount_setattr.argc 0
    0
;

macro syscall.quotactl_fd 0
    443
    syscall0
;

macro syscall.quotactl_fd.num 0
    443
;

macro syscall.quotactl_fd.argc 0
    0
;

macro syscall.landlock_create_ruleset 0
    444
    syscall0
;

macro syscall.landlock_create_ruleset.num 0
    444
;

macro syscall.landlock_create_ruleset.argc 0
    0
;

macro syscall.landlock_add_rule 0
    445
    syscall0
;

macro syscall.landlock_add_rule.num 0
    445
;

macro syscall.landlock_add_rule.argc 0
    0
;

macro syscall.landlock_restrict_self 0
    446
    syscall0
;

macro syscall.landlock_restrict_self.num 0
    446
;

macro syscall.landlock_restrict_self.argc 0
    0
;

macro syscall.memfd_secret 0
    447
    syscall0
;

macro syscall.memfd_secret.num 0
    447
;

macro syscall.memfd_secret.argc 0
    0
;

macro syscall.process_mrelease 0
    448
    syscall0
;

macro syscall.process_mrelease.num 0
    448
;

macro syscall.process_mrelease.argc 0
    0
;

macro syscall.futex_waitv 0
    449
    syscall0
;

macro syscall.futex_waitv.num 0
    449
;

macro syscall.futex_waitv.argc 0
    0
;

macro syscall.set_mempolicy_home_node 0
    450
    syscall0
;

macro syscall.set_mempolicy_home_node.num 0
    450
;

macro syscall.set_mempolicy_home_node.argc 0
    0
;

macro syscall.cachestat 0
    451
    syscall0
;

macro syscall.cachestat.num 0
    451
;

macro syscall.cachestat.argc 0
    0
;

macro syscall.fchmodat2 0
    452
    syscall0
;

macro syscall.fchmodat2.num 0
    452
;

macro syscall.fchmodat2.argc 0
    0
;

macro syscall.map_shadow_stack 0
    453
    syscall0
;

macro syscall.map_shadow_stack.num 0
    453
;

macro syscall.map_shadow_stack.argc 0
    0
;

macro syscall.futex_wake 0
    454
    syscall0
;

macro syscall.futex_wake.num 0
    454
;

macro syscall.futex_wake.argc 0
    0
;

macro syscall.futex_wait 0
    455
    syscall0
;

macro syscall.futex_wait.num 0
    455
;

macro syscall.futex_wait.argc 0
    0
;

macro syscall.futex_requeue 0
    456
    syscall0
;

macro syscall.futex_requeue.num 0
    456
;

macro syscall.futex_requeue.argc 0
    0
;

macro syscall.statmount 0
    457
    syscall0
;

macro syscall.statmount.num 0
    457
;

macro syscall.statmount.argc 0
    0
;

macro syscall.listmount 0
    458
    syscall0
;

macro syscall.listmount.num 0
    458
;

macro syscall.listmount.argc 0
    0
;

macro syscall.lsm_get_self_attr 0
    459
    syscall0
;

macro syscall.lsm_get_self_attr.num 0
    459
;

macro syscall.lsm_get_self_attr.argc 0
    0
;

macro syscall.lsm_set_self_attr 0
    460
    syscall0
;

macro syscall.lsm_set_self_attr.num 0
    460
;

macro syscall.lsm_set_self_attr.argc 0
    0
;

macro syscall.lsm_list_modules 0
    461
    syscall0
;

macro syscall.lsm_list_modules.num 0
    461
;

macro syscall.lsm_list_modules.argc 0
    0
;

macro syscall.mseal 0
    462
    syscall0
;

macro syscall.mseal.num 0
    462
;

macro syscall.mseal.argc 0
    0
;

macro syscall.setxattrat 0
    463
    syscall0
;

macro syscall.setxattrat.num 0
    463
;

macro syscall.setxattrat.argc 0
    0
;

macro syscall.getxattrat 0
    464
    syscall0
;

macro syscall.getxattrat.num 0
    464
;

macro syscall.getxattrat.argc 0
    0
;

macro syscall.listxattrat 0
    465
    syscall0
;

macro syscall.listxattrat.num 0
    465
;

macro syscall.listxattrat.argc 0
    0
;

macro syscall.removexattrat 0
    466
    syscall0
;

macro syscall.removexattrat.num 0
    466
;

macro syscall.removexattrat.argc 0
    0
;

macro syscall.open_tree_attr 0
    467
    syscall0
;

macro syscall.open_tree_attr.num 0
    467
;

macro syscall.open_tree_attr.argc 0
    0
;

macro syscall.file_getattr 0
    468
    syscall0
;

macro syscall.file_getattr.num 0
    468
;

macro syscall.file_getattr.argc 0
    0
;

macro syscall.file_setattr 0
    469
    syscall0
;

macro syscall.file_setattr.num 0
    469
;

macro syscall.file_setattr.argc 0
    0
;

macro syscall.listns 0
    470
    syscall0
;

macro syscall.listns.num 0
    470
;

macro syscall.listns.argc 0
    0
;

macro syscall.compat_sys_rt_sigaction 0
    512
    syscall0
;

macro syscall.compat_sys_rt_sigaction.num 0
    512
;

macro syscall.compat_sys_rt_sigaction.argc 0
    0
;

macro syscall.compat_sys_x32_rt_sigreturn 0
    513
    syscall0
;

macro syscall.compat_sys_x32_rt_sigreturn.num 0
    513
;

macro syscall.compat_sys_x32_rt_sigreturn.argc 0
    0
;

macro syscall.compat_sys_ioctl 0
    514
    syscall0
;

macro syscall.compat_sys_ioctl.num 0
    514
;

macro syscall.compat_sys_ioctl.argc 0
    0
;

macro syscall.compat_sys_recvfrom 0
    517
    syscall0
;

macro syscall.compat_sys_recvfrom.num 0
    517
;

macro syscall.compat_sys_recvfrom.argc 0
    0
;

macro syscall.compat_sys_sendmsg 0
    518
    syscall0
;

macro syscall.compat_sys_sendmsg.num 0
    518
;

macro syscall.compat_sys_sendmsg.argc 0
    0
;

macro syscall.compat_sys_recvmsg 0
    519
    syscall0
;

macro syscall.compat_sys_recvmsg.num 0
    519
;

macro syscall.compat_sys_recvmsg.argc 0
    0
;

macro syscall.compat_sys_execve 0
    520
    syscall0
;

macro syscall.compat_sys_execve.num 0
    520
;

macro syscall.compat_sys_execve.argc 0
    0
;

macro syscall.compat_sys_ptrace 0
    521
    syscall0
;

macro syscall.compat_sys_ptrace.num 0
    521
;

macro syscall.compat_sys_ptrace.argc 0
    0
;

macro syscall.compat_sys_rt_sigpending 0
    522
    syscall0
;

macro syscall.compat_sys_rt_sigpending.num 0
    522
;

macro syscall.compat_sys_rt_sigpending.argc 0
    0
;

macro syscall.compat_sys_rt_sigtimedwait_time64 0
    523
    syscall0
;

macro syscall.compat_sys_rt_sigtimedwait_time64.num 0
    523
;

macro syscall.compat_sys_rt_sigtimedwait_time64.argc 0
    0
;

macro syscall.compat_sys_rt_sigqueueinfo 0
    524
    syscall0
;

macro syscall.compat_sys_rt_sigqueueinfo.num 0
    524
;

macro syscall.compat_sys_rt_sigqueueinfo.argc 0
    0
;

macro syscall.compat_sys_sigaltstack 0
    525
    syscall0
;

macro syscall.compat_sys_sigaltstack.num 0
    525
;

macro syscall.compat_sys_sigaltstack.argc 0
    0
;

macro syscall.compat_sys_timer_create 0
    526
    syscall0
;

macro syscall.compat_sys_timer_create.num 0
    526
;

macro syscall.compat_sys_timer_create.argc 0
    0
;

macro syscall.compat_sys_mq_notify 0
    527
    syscall0
;

macro syscall.compat_sys_mq_notify.num 0
    527
;

macro syscall.compat_sys_mq_notify.argc 0
    0
;

macro syscall.compat_sys_kexec_load 0
    528
    syscall0
;

macro syscall.compat_sys_kexec_load.num 0
    528
;

macro syscall.compat_sys_kexec_load.argc 0
    0
;

macro syscall.compat_sys_waitid 0
    529
    syscall0
;

macro syscall.compat_sys_waitid.num 0
    529
;

macro syscall.compat_sys_waitid.argc 0
    0
;

macro syscall.compat_sys_set_robust_list 0
    530
    syscall0
;

macro syscall.compat_sys_set_robust_list.num 0
    530
;

macro syscall.compat_sys_set_robust_list.argc 0
    0
;

macro syscall.compat_sys_get_robust_list 0
    531
    syscall0
;

macro syscall.compat_sys_get_robust_list.num 0
    531
;

macro syscall.compat_sys_get_robust_list.argc 0
    0
;

macro syscall.compat_sys_preadv64 0
    534
    syscall0
;

macro syscall.compat_sys_preadv64.num 0
    534
;

macro syscall.compat_sys_preadv64.argc 0
    0
;

macro syscall.compat_sys_pwritev64 0
    535
    syscall0
;

macro syscall.compat_sys_pwritev64.num 0
    535
;

macro syscall.compat_sys_pwritev64.argc 0
    0
;

macro syscall.compat_sys_rt_tgsigqueueinfo 0
    536
    syscall0
;

macro syscall.compat_sys_rt_tgsigqueueinfo.num 0
    536
;

macro syscall.compat_sys_rt_tgsigqueueinfo.argc 0
    0
;

macro syscall.compat_sys_recvmmsg_time64 0
    537
    syscall0
;

macro syscall.compat_sys_recvmmsg_time64.num 0
    537
;

macro syscall.compat_sys_recvmmsg_time64.argc 0
    0
;

macro syscall.compat_sys_sendmmsg 0
    538
    syscall0
;

macro syscall.compat_sys_sendmmsg.num 0
    538
;

macro syscall.compat_sys_sendmmsg.argc 0
    0
;

macro syscall.compat_sys_io_setup 0
    543
    syscall0
;

macro syscall.compat_sys_io_setup.num 0
    543
;

macro syscall.compat_sys_io_setup.argc 0
    0
;

macro syscall.compat_sys_io_submit 0
    544
    syscall0
;

macro syscall.compat_sys_io_submit.num 0
    544
;

macro syscall.compat_sys_io_submit.argc 0
    0
;

macro syscall.compat_sys_execveat 0
    545
    syscall0
;

macro syscall.compat_sys_execveat.num 0
    545
;

macro syscall.compat_sys_execveat.argc 0
    0
;

macro syscall.compat_sys_preadv64v2 0
    546
    syscall0
;

macro syscall.compat_sys_preadv64v2.num 0
    546
;

macro syscall.compat_sys_preadv64v2.argc 0
    0
;

macro syscall.compat_sys_pwritev64v2 0
    547
    syscall0
;

macro syscall.compat_sys_pwritev64v2.num 0
    547
;

macro syscall.compat_sys_pwritev64v2.argc 0
    0
;
