import stdlib.sl
import meta.sl

word verify_ct_word_inventory_coverage
  "CT" meta-word-exists static_assert
  "add-token" meta-word-exists static_assert
  "add-token-chars" meta-word-exists static_assert
  "bss-append" meta-word-exists static_assert
  "bss-clear" meta-word-exists static_assert
  "bss-set" meta-word-exists static_assert
  "clear-token-hook" meta-word-exists static_assert
  "ct-add-grammar-rewrite" meta-word-exists static_assert
  "ct-add-grammar-rewrite-named" meta-word-exists static_assert
  "ct-add-grammar-rewrite-priority" meta-word-exists static_assert
  "ct-add-reader-rewrite" meta-word-exists static_assert
  "ct-add-reader-rewrite-named" meta-word-exists static_assert
  "ct-add-reader-rewrite-priority" meta-word-exists static_assert
  "ct-capture-args" meta-word-exists static_assert
  "ct-capture-assert-shape" meta-word-exists static_assert
  "ct-capture-clone" meta-word-exists static_assert
  "ct-capture-coerce-number" meta-word-exists static_assert
  "ct-capture-coerce-string" meta-word-exists static_assert
  "ct-capture-coerce-tokens" meta-word-exists static_assert
  "ct-capture-compress" meta-word-exists static_assert
  "ct-capture-count" meta-word-exists static_assert
  "ct-capture-decompress" meta-word-exists static_assert
  "ct-capture-deserialize" meta-word-exists static_assert
  "ct-capture-diff" meta-word-exists static_assert
  "ct-capture-equal?" meta-word-exists static_assert
  "ct-capture-filter" meta-word-exists static_assert
  "ct-capture-freeze" meta-word-exists static_assert
  "ct-capture-get" meta-word-exists static_assert
  "ct-capture-global-clear" meta-word-exists static_assert
  "ct-capture-global-delete" meta-word-exists static_assert
  "ct-capture-global-get" meta-word-exists static_assert
  "ct-capture-global-set" meta-word-exists static_assert
  "ct-capture-globals" meta-word-exists static_assert
  "ct-capture-has?" meta-word-exists static_assert
  "ct-capture-hash" meta-word-exists static_assert
  "ct-capture-join" meta-word-exists static_assert
  "ct-capture-lifetime" meta-word-exists static_assert
  "ct-capture-lifetime-assert" meta-word-exists static_assert
  "ct-capture-lifetime-live?" meta-word-exists static_assert
  "ct-capture-lint" meta-word-exists static_assert
  "ct-capture-locals" meta-word-exists static_assert
  "ct-capture-map" meta-word-exists static_assert
  "ct-capture-mutable?" meta-word-exists static_assert
  "ct-capture-normalize" meta-word-exists static_assert
  "ct-capture-origin" meta-word-exists static_assert
  "ct-capture-pretty" meta-word-exists static_assert
  "ct-capture-replay-clear" meta-word-exists static_assert
  "ct-capture-replay-log" meta-word-exists static_assert
  "ct-capture-schema-get" meta-word-exists static_assert
  "ct-capture-schema-put" meta-word-exists static_assert
  "ct-capture-schema-validate" meta-word-exists static_assert
  "ct-capture-separate" meta-word-exists static_assert
  "ct-capture-serialize" meta-word-exists static_assert
  "ct-capture-shape" meta-word-exists static_assert
  "ct-capture-slice" meta-word-exists static_assert
  "ct-capture-taint-get" meta-word-exists static_assert
  "ct-capture-taint-set" meta-word-exists static_assert
  "ct-capture-tainted?" meta-word-exists static_assert
  "ct-capture-thaw" meta-word-exists static_assert
  "ct-clear-ct-call-memo" meta-word-exists static_assert
  "ct-clear-ct-call-side-effect-log" meta-word-exists static_assert
  "ct-clear-grammar-rewrites" meta-word-exists static_assert
  "ct-clear-reader-rewrites" meta-word-exists static_assert
  "ct-clear-rewrite-loop-reports" meta-word-exists static_assert
  "ct-clear-rewrite-profile" meta-word-exists static_assert
  "ct-clear-rewrite-trace-log" meta-word-exists static_assert
  "ct-clone-macro" meta-word-exists static_assert
  "ct-control-add-close-op" meta-word-exists static_assert
  "ct-control-depth" meta-word-exists static_assert
  "ct-control-frame-new" meta-word-exists static_assert
  "ct-control-get" meta-word-exists static_assert
  "ct-control-peek" meta-word-exists static_assert
  "ct-control-pop" meta-word-exists static_assert
  "ct-control-push" meta-word-exists static_assert
  "ct-control-set" meta-word-exists static_assert
  "ct-ctrand-int" meta-word-exists static_assert
  "ct-ctrand-range" meta-word-exists static_assert
  "ct-ctrand-seed" meta-word-exists static_assert
  "ct-current-token" meta-word-exists static_assert
  "ct-detect-pattern-conflicts" meta-word-exists static_assert
  "ct-detect-pattern-conflicts-named" meta-word-exists static_assert
  "ct-emit-op" meta-word-exists static_assert
  "ct-export-rewrite-pack" meta-word-exists static_assert
  "ct-gensym" meta-word-exists static_assert
  "ct-get-ct-call-contract" meta-word-exists static_assert
  "ct-get-ct-call-exception-policy" meta-word-exists static_assert
  "ct-get-ct-call-memo" meta-word-exists static_assert
  "ct-get-ct-call-memo-size" meta-word-exists static_assert
  "ct-get-ct-call-recursion-limit" meta-word-exists static_assert
  "ct-get-ct-call-sandbox-allowlist" meta-word-exists static_assert
  "ct-get-ct-call-sandbox-mode" meta-word-exists static_assert
  "ct-get-ct-call-side-effect-log" meta-word-exists static_assert
  "ct-get-ct-call-side-effects" meta-word-exists static_assert
  "ct-get-ct-call-timeout-ms" meta-word-exists static_assert
  "ct-get-grammar-rewrite-enabled" meta-word-exists static_assert
  "ct-get-grammar-rewrite-priority" meta-word-exists static_assert
  "ct-get-macro-expansion" meta-word-exists static_assert
  "ct-get-macro-expansion-limit" meta-word-exists static_assert
  "ct-get-macro-preview" meta-word-exists static_assert
  "ct-get-macro-signature" meta-word-exists static_assert
  "ct-get-macro-template-mode" meta-word-exists static_assert
  "ct-get-macro-template-program-size" meta-word-exists static_assert
  "ct-get-macro-template-version" meta-word-exists static_assert
  "ct-get-pattern-macro-clause-details" meta-word-exists static_assert
  "ct-get-pattern-macro-clauses" meta-word-exists static_assert
  "ct-get-pattern-macro-enabled" meta-word-exists static_assert
  "ct-get-pattern-macro-group" meta-word-exists static_assert
  "ct-get-pattern-macro-priority" meta-word-exists static_assert
  "ct-get-pattern-macro-scope" meta-word-exists static_assert
  "ct-get-reader-rewrite-enabled" meta-word-exists static_assert
  "ct-get-reader-rewrite-priority" meta-word-exists static_assert
  "ct-get-rewrite-index-stats" meta-word-exists static_assert
  "ct-get-rewrite-loop-detection" meta-word-exists static_assert
  "ct-get-rewrite-loop-reports" meta-word-exists static_assert
  "ct-get-rewrite-max-steps" meta-word-exists static_assert
  "ct-get-rewrite-pipeline" meta-word-exists static_assert
  "ct-get-rewrite-profile" meta-word-exists static_assert
  "ct-get-rewrite-provenance" meta-word-exists static_assert
  "ct-get-rewrite-saturation" meta-word-exists static_assert
  "ct-get-rewrite-specificity" meta-word-exists static_assert
  "ct-get-rewrite-trace" meta-word-exists static_assert
  "ct-get-rewrite-trace-log" meta-word-exists static_assert
  "ct-get-word-asm" meta-word-exists static_assert
  "ct-get-word-body" meta-word-exists static_assert
  "ct-import-rewrite-pack" meta-word-exists static_assert
  "ct-import-rewrite-pack-replace" meta-word-exists static_assert
  "ct-last-token-line" meta-word-exists static_assert
  "ct-list-active-pattern-groups" meta-word-exists static_assert
  "ct-list-active-pattern-scopes" meta-word-exists static_assert
  "ct-list-grammar-rewrites" meta-word-exists static_assert
  "ct-list-pattern-macros" meta-word-exists static_assert
  "ct-list-reader-rewrites" meta-word-exists static_assert
  "ct-list-rewrite-active-pipelines" meta-word-exists static_assert
  "ct-list-words" meta-word-exists static_assert
  "ct-list-words-prefix" meta-word-exists static_assert
  "ct-macro-attrs-get" meta-word-exists static_assert
  "ct-macro-attrs-set" meta-word-exists static_assert
  "ct-macro-doc-get" meta-word-exists static_assert
  "ct-macro-doc-set" meta-word-exists static_assert
  "ct-new-label" meta-word-exists static_assert
  "ct-parser-pos" meta-word-exists static_assert
  "ct-parser-remaining" meta-word-exists static_assert
  "ct-rebuild-rewrite-index" meta-word-exists static_assert
  "ct-register-block-opener" meta-word-exists static_assert
  "ct-register-control-override" meta-word-exists static_assert
  "ct-register-pattern-macro" meta-word-exists static_assert
  "ct-register-text-macro" meta-word-exists static_assert
  "ct-register-text-macro-signature" meta-word-exists static_assert
  "ct-remove-grammar-rewrite" meta-word-exists static_assert
  "ct-remove-reader-rewrite" meta-word-exists static_assert
  "ct-rename-macro" meta-word-exists static_assert
  "ct-rewrite-compatibility-matrix" meta-word-exists static_assert
  "ct-rewrite-dry-run" meta-word-exists static_assert
  "ct-rewrite-generate-fixture" meta-word-exists static_assert
  "ct-rewrite-txn-begin" meta-word-exists static_assert
  "ct-rewrite-txn-commit" meta-word-exists static_assert
  "ct-rewrite-txn-rollback" meta-word-exists static_assert
  "ct-set-ct-call-contract" meta-word-exists static_assert
  "ct-set-ct-call-exception-policy" meta-word-exists static_assert
  "ct-set-ct-call-memo" meta-word-exists static_assert
  "ct-set-ct-call-recursion-limit" meta-word-exists static_assert
  "ct-set-ct-call-sandbox-allowlist" meta-word-exists static_assert
  "ct-set-ct-call-sandbox-mode" meta-word-exists static_assert
  "ct-set-ct-call-side-effects" meta-word-exists static_assert
  "ct-set-ct-call-timeout-ms" meta-word-exists static_assert
  "ct-set-grammar-rewrite-enabled" meta-word-exists static_assert
  "ct-set-grammar-rewrite-priority" meta-word-exists static_assert
  "ct-set-macro-expansion" meta-word-exists static_assert
  "ct-set-macro-expansion-limit" meta-word-exists static_assert
  "ct-set-macro-preview" meta-word-exists static_assert
  "ct-set-pattern-group-active" meta-word-exists static_assert
  "ct-set-pattern-macro-clause-guard" meta-word-exists static_assert
  "ct-set-pattern-macro-enabled" meta-word-exists static_assert
  "ct-set-pattern-macro-group" meta-word-exists static_assert
  "ct-set-pattern-macro-priority" meta-word-exists static_assert
  "ct-set-pattern-macro-scope" meta-word-exists static_assert
  "ct-set-pattern-scope-active" meta-word-exists static_assert
  "ct-set-reader-rewrite-enabled" meta-word-exists static_assert
  "ct-set-reader-rewrite-priority" meta-word-exists static_assert
  "ct-set-rewrite-loop-detection" meta-word-exists static_assert
  "ct-set-rewrite-max-steps" meta-word-exists static_assert
  "ct-set-rewrite-pipeline" meta-word-exists static_assert
  "ct-set-rewrite-pipeline-active" meta-word-exists static_assert
  "ct-set-rewrite-saturation" meta-word-exists static_assert
  "ct-set-rewrite-trace" meta-word-exists static_assert
  "ct-unregister-block-opener" meta-word-exists static_assert
  "ct-unregister-control-override" meta-word-exists static_assert
  "ct-unregister-pattern-macro" meta-word-exists static_assert
  "ct-unregister-word" meta-word-exists static_assert
  "ct-word-exists?" meta-word-exists static_assert
  "ct-word-is-pattern-macro" meta-word-exists static_assert
  "ct-word-is-text-macro" meta-word-exists static_assert
  "emit-definition" meta-word-exists static_assert
  "eval" meta-word-exists static_assert
  "i" meta-word-exists static_assert
  "identifier?" meta-word-exists static_assert
  "inject-tokens" meta-word-exists static_assert
  "int>string" meta-word-exists static_assert
  "lexer-collect-brace" meta-word-exists static_assert
  "lexer-expect" meta-word-exists static_assert
  "lexer-new" meta-word-exists static_assert
  "lexer-peek" meta-word-exists static_assert
  "lexer-pop" meta-word-exists static_assert
  "lexer-push-back" meta-word-exists static_assert
  "list-append" meta-word-exists static_assert
  "list-clear" meta-word-exists static_assert
  "list-clone" meta-word-exists static_assert
  "list-contains?" meta-word-exists static_assert
  "list-empty?" meta-word-exists static_assert
  "list-extend" meta-word-exists static_assert
  "list-find" meta-word-exists static_assert
  "list-get" meta-word-exists static_assert
  "list-insert" meta-word-exists static_assert
  "list-join" meta-word-exists static_assert
  "list-last" meta-word-exists static_assert
  "list-length" meta-word-exists static_assert
  "list-new" meta-word-exists static_assert
  "list-peek-front" meta-word-exists static_assert
  "list-pop" meta-word-exists static_assert
  "list-pop-front" meta-word-exists static_assert
  "list-push-front" meta-word-exists static_assert
  "list-remove" meta-word-exists static_assert
  "list-reverse" meta-word-exists static_assert
  "list-set" meta-word-exists static_assert
  "list-slice" meta-word-exists static_assert
  "map-clear" meta-word-exists static_assert
  "map-clone" meta-word-exists static_assert
  "map-delete" meta-word-exists static_assert
  "map-empty?" meta-word-exists static_assert
  "map-get" meta-word-exists static_assert
  "map-has?" meta-word-exists static_assert
  "map-keys" meta-word-exists static_assert
  "map-length" meta-word-exists static_assert
  "map-new" meta-word-exists static_assert
  "map-set" meta-word-exists static_assert
  "map-update" meta-word-exists static_assert
  "map-values" meta-word-exists static_assert
  "next-token" meta-word-exists static_assert
  "nil" meta-word-exists static_assert
  "nil?" meta-word-exists static_assert
  "parse-error" meta-word-exists static_assert
  "peek-token" meta-word-exists static_assert
  "prelude-append" meta-word-exists static_assert
  "prelude-clear" meta-word-exists static_assert
  "prelude-set" meta-word-exists static_assert
  "set-token-hook" meta-word-exists static_assert
  "shunt" meta-word-exists static_assert
  "static_assert" meta-word-exists static_assert
  "string-append" meta-word-exists static_assert
  "string-contains?" meta-word-exists static_assert
  "string-ends-with?" meta-word-exists static_assert
  "string-join" meta-word-exists static_assert
  "string-length" meta-word-exists static_assert
  "string-lower" meta-word-exists static_assert
  "string-replace" meta-word-exists static_assert
  "string-split" meta-word-exists static_assert
  "string-starts-with?" meta-word-exists static_assert
  "string-strip" meta-word-exists static_assert
  "string-upper" meta-word-exists static_assert
  "string=" meta-word-exists static_assert
  "string>number" meta-word-exists static_assert
  "token-column" meta-word-exists static_assert
  "token-from-lexeme" meta-word-exists static_assert
  "token-lexeme" meta-word-exists static_assert
  "token-line" meta-word-exists static_assert
  "use-l2-ct" meta-word-exists static_assert
end
compile-time verify_ct_word_inventory_coverage

word main
  1 puti cr
end
