import stdlib.sl
import meta.sl

word verify_meta_ct_wrapper_coverage
  "meta-capture-args" meta-word-exists static_assert
  "ct-capture-args" meta-word-exists static_assert
  "meta-capture-assert-shape" meta-word-exists static_assert
  "ct-capture-assert-shape" meta-word-exists static_assert
  "meta-capture-clone" meta-word-exists static_assert
  "ct-capture-clone" meta-word-exists static_assert
  "meta-capture-coerce-number" meta-word-exists static_assert
  "ct-capture-coerce-number" meta-word-exists static_assert
  "meta-capture-coerce-string" meta-word-exists static_assert
  "ct-capture-coerce-string" meta-word-exists static_assert
  "meta-capture-coerce-tokens" meta-word-exists static_assert
  "ct-capture-coerce-tokens" meta-word-exists static_assert
  "meta-capture-compress" meta-word-exists static_assert
  "ct-capture-compress" meta-word-exists static_assert
  "meta-capture-count" meta-word-exists static_assert
  "ct-capture-count" meta-word-exists static_assert
  "meta-capture-decompress" meta-word-exists static_assert
  "ct-capture-decompress" meta-word-exists static_assert
  "meta-capture-deserialize" meta-word-exists static_assert
  "ct-capture-deserialize" meta-word-exists static_assert
  "meta-capture-diff" meta-word-exists static_assert
  "ct-capture-diff" meta-word-exists static_assert
  "meta-capture-equal" meta-word-exists static_assert
  "ct-capture-equal?" meta-word-exists static_assert
  "meta-capture-filter" meta-word-exists static_assert
  "ct-capture-filter" meta-word-exists static_assert
  "meta-capture-freeze" meta-word-exists static_assert
  "ct-capture-freeze" meta-word-exists static_assert
  "meta-capture-get" meta-word-exists static_assert
  "ct-capture-get" meta-word-exists static_assert
  "meta-capture-global-clear" meta-word-exists static_assert
  "ct-capture-global-clear" meta-word-exists static_assert
  "meta-capture-global-delete" meta-word-exists static_assert
  "ct-capture-global-delete" meta-word-exists static_assert
  "meta-capture-global-get" meta-word-exists static_assert
  "ct-capture-global-get" meta-word-exists static_assert
  "meta-capture-global-set" meta-word-exists static_assert
  "ct-capture-global-set" meta-word-exists static_assert
  "meta-capture-globals" meta-word-exists static_assert
  "ct-capture-globals" meta-word-exists static_assert
  "meta-capture-has" meta-word-exists static_assert
  "ct-capture-has?" meta-word-exists static_assert
  "meta-capture-hash" meta-word-exists static_assert
  "ct-capture-hash" meta-word-exists static_assert
  "meta-capture-join" meta-word-exists static_assert
  "ct-capture-join" meta-word-exists static_assert
  "meta-capture-lifetime" meta-word-exists static_assert
  "ct-capture-lifetime" meta-word-exists static_assert
  "meta-capture-lifetime-assert" meta-word-exists static_assert
  "ct-capture-lifetime-assert" meta-word-exists static_assert
  "meta-capture-lifetime-live" meta-word-exists static_assert
  "ct-capture-lifetime-live?" meta-word-exists static_assert
  "meta-capture-lint" meta-word-exists static_assert
  "ct-capture-lint" meta-word-exists static_assert
  "meta-capture-locals" meta-word-exists static_assert
  "ct-capture-locals" meta-word-exists static_assert
  "meta-capture-map" meta-word-exists static_assert
  "ct-capture-map" meta-word-exists static_assert
  "meta-capture-mutable" meta-word-exists static_assert
  "ct-capture-mutable?" meta-word-exists static_assert
  "meta-capture-normalize" meta-word-exists static_assert
  "ct-capture-normalize" meta-word-exists static_assert
  "meta-capture-origin" meta-word-exists static_assert
  "ct-capture-origin" meta-word-exists static_assert
  "meta-capture-pretty" meta-word-exists static_assert
  "ct-capture-pretty" meta-word-exists static_assert
  "meta-capture-replay-clear" meta-word-exists static_assert
  "ct-capture-replay-clear" meta-word-exists static_assert
  "meta-capture-replay-log" meta-word-exists static_assert
  "ct-capture-replay-log" meta-word-exists static_assert
  "meta-capture-schema-get" meta-word-exists static_assert
  "ct-capture-schema-get" meta-word-exists static_assert
  "meta-capture-schema-put" meta-word-exists static_assert
  "ct-capture-schema-put" meta-word-exists static_assert
  "meta-capture-schema-validate" meta-word-exists static_assert
  "ct-capture-schema-validate" meta-word-exists static_assert
  "meta-capture-separate" meta-word-exists static_assert
  "ct-capture-separate" meta-word-exists static_assert
  "meta-capture-serialize" meta-word-exists static_assert
  "ct-capture-serialize" meta-word-exists static_assert
  "meta-capture-shape" meta-word-exists static_assert
  "ct-capture-shape" meta-word-exists static_assert
  "meta-capture-slice" meta-word-exists static_assert
  "ct-capture-slice" meta-word-exists static_assert
  "meta-capture-taint-get" meta-word-exists static_assert
  "ct-capture-taint-get" meta-word-exists static_assert
  "meta-capture-taint-set" meta-word-exists static_assert
  "ct-capture-taint-set" meta-word-exists static_assert
  "meta-capture-tainted" meta-word-exists static_assert
  "ct-capture-tainted?" meta-word-exists static_assert
  "meta-capture-thaw" meta-word-exists static_assert
  "ct-capture-thaw" meta-word-exists static_assert
  "meta-ct-call-contract-get" meta-word-exists static_assert
  "ct-get-ct-call-contract" meta-word-exists static_assert
  "meta-ct-call-contract-set" meta-word-exists static_assert
  "ct-set-ct-call-contract" meta-word-exists static_assert
  "meta-ct-call-exception-policy-get" meta-word-exists static_assert
  "ct-get-ct-call-exception-policy" meta-word-exists static_assert
  "meta-ct-call-exception-policy-set" meta-word-exists static_assert
  "ct-set-ct-call-exception-policy" meta-word-exists static_assert
  "meta-ct-call-memo-clear" meta-word-exists static_assert
  "ct-clear-ct-call-memo" meta-word-exists static_assert
  "meta-ct-call-memo-get" meta-word-exists static_assert
  "ct-get-ct-call-memo" meta-word-exists static_assert
  "meta-ct-call-memo-set" meta-word-exists static_assert
  "ct-set-ct-call-memo" meta-word-exists static_assert
  "meta-ct-call-memo-size" meta-word-exists static_assert
  "ct-get-ct-call-memo-size" meta-word-exists static_assert
  "meta-ct-call-recursion-limit-get" meta-word-exists static_assert
  "ct-get-ct-call-recursion-limit" meta-word-exists static_assert
  "meta-ct-call-recursion-limit-set" meta-word-exists static_assert
  "ct-set-ct-call-recursion-limit" meta-word-exists static_assert
  "meta-ct-call-sandbox-allowlist-get" meta-word-exists static_assert
  "ct-get-ct-call-sandbox-allowlist" meta-word-exists static_assert
  "meta-ct-call-sandbox-allowlist-set" meta-word-exists static_assert
  "ct-set-ct-call-sandbox-allowlist" meta-word-exists static_assert
  "meta-ct-call-sandbox-mode-get" meta-word-exists static_assert
  "ct-get-ct-call-sandbox-mode" meta-word-exists static_assert
  "meta-ct-call-sandbox-mode-set" meta-word-exists static_assert
  "ct-set-ct-call-sandbox-mode" meta-word-exists static_assert
  "meta-ct-call-side-effects-clear" meta-word-exists static_assert
  "ct-clear-ct-call-side-effect-log" meta-word-exists static_assert
  "meta-ct-call-side-effects-get" meta-word-exists static_assert
  "ct-get-ct-call-side-effects" meta-word-exists static_assert
  "meta-ct-call-side-effects-log" meta-word-exists static_assert
  "ct-get-ct-call-side-effect-log" meta-word-exists static_assert
  "meta-ct-call-side-effects-set" meta-word-exists static_assert
  "ct-set-ct-call-side-effects" meta-word-exists static_assert
  "meta-ct-call-timeout-ms-get" meta-word-exists static_assert
  "ct-get-ct-call-timeout-ms" meta-word-exists static_assert
  "meta-ct-call-timeout-ms-set" meta-word-exists static_assert
  "ct-set-ct-call-timeout-ms" meta-word-exists static_assert
  "meta-ct-rand-int" meta-word-exists static_assert
  "ct-ctrand-int" meta-word-exists static_assert
  "meta-ct-rand-range" meta-word-exists static_assert
  "ct-ctrand-range" meta-word-exists static_assert
  "meta-ct-rand-seed" meta-word-exists static_assert
  "ct-ctrand-seed" meta-word-exists static_assert
  "meta-current-token" meta-word-exists static_assert
  "ct-current-token" meta-word-exists static_assert
  "meta-gensym" meta-word-exists static_assert
  "ct-gensym" meta-word-exists static_assert
  "meta-grammar-add" meta-word-exists static_assert
  "ct-add-grammar-rewrite" meta-word-exists static_assert
  "meta-grammar-add-named" meta-word-exists static_assert
  "ct-add-grammar-rewrite-named" meta-word-exists static_assert
  "meta-grammar-add-priority" meta-word-exists static_assert
  "ct-add-grammar-rewrite-priority" meta-word-exists static_assert
  "meta-grammar-clear" meta-word-exists static_assert
  "ct-clear-grammar-rewrites" meta-word-exists static_assert
  "meta-grammar-enabled-get" meta-word-exists static_assert
  "ct-get-grammar-rewrite-enabled" meta-word-exists static_assert
  "meta-grammar-enabled-set" meta-word-exists static_assert
  "ct-set-grammar-rewrite-enabled" meta-word-exists static_assert
  "meta-grammar-list" meta-word-exists static_assert
  "ct-list-grammar-rewrites" meta-word-exists static_assert
  "meta-grammar-priority-get" meta-word-exists static_assert
  "ct-get-grammar-rewrite-priority" meta-word-exists static_assert
  "meta-grammar-priority-set" meta-word-exists static_assert
  "ct-set-grammar-rewrite-priority" meta-word-exists static_assert
  "meta-grammar-remove" meta-word-exists static_assert
  "ct-remove-grammar-rewrite" meta-word-exists static_assert
  "meta-macro-attrs-get" meta-word-exists static_assert
  "ct-macro-attrs-get" meta-word-exists static_assert
  "meta-macro-attrs-set" meta-word-exists static_assert
  "ct-macro-attrs-set" meta-word-exists static_assert
  "meta-macro-clone" meta-word-exists static_assert
  "ct-clone-macro" meta-word-exists static_assert
  "meta-macro-doc-get" meta-word-exists static_assert
  "ct-macro-doc-get" meta-word-exists static_assert
  "meta-macro-doc-set" meta-word-exists static_assert
  "ct-macro-doc-set" meta-word-exists static_assert
  "meta-macro-expansion-get" meta-word-exists static_assert
  "ct-get-macro-expansion" meta-word-exists static_assert
  "meta-macro-expansion-set" meta-word-exists static_assert
  "ct-set-macro-expansion" meta-word-exists static_assert
  "meta-macro-is-pattern" meta-word-exists static_assert
  "ct-word-is-pattern-macro" meta-word-exists static_assert
  "meta-macro-is-text" meta-word-exists static_assert
  "ct-word-is-text-macro" meta-word-exists static_assert
  "meta-macro-limit-get" meta-word-exists static_assert
  "ct-get-macro-expansion-limit" meta-word-exists static_assert
  "meta-macro-limit-set" meta-word-exists static_assert
  "ct-set-macro-expansion-limit" meta-word-exists static_assert
  "meta-macro-pattern-clause-details" meta-word-exists static_assert
  "ct-get-pattern-macro-clause-details" meta-word-exists static_assert
  "meta-macro-pattern-clause-guard-set" meta-word-exists static_assert
  "ct-set-pattern-macro-clause-guard" meta-word-exists static_assert
  "meta-macro-pattern-clauses" meta-word-exists static_assert
  "ct-get-pattern-macro-clauses" meta-word-exists static_assert
  "meta-macro-pattern-conflicts" meta-word-exists static_assert
  "ct-detect-pattern-conflicts" meta-word-exists static_assert
  "meta-macro-pattern-conflicts-named" meta-word-exists static_assert
  "ct-detect-pattern-conflicts-named" meta-word-exists static_assert
  "meta-macro-pattern-enabled-get" meta-word-exists static_assert
  "ct-get-pattern-macro-enabled" meta-word-exists static_assert
  "meta-macro-pattern-enabled-set" meta-word-exists static_assert
  "ct-set-pattern-macro-enabled" meta-word-exists static_assert
  "meta-macro-pattern-group-active-set" meta-word-exists static_assert
  "ct-set-pattern-group-active" meta-word-exists static_assert
  "meta-macro-pattern-group-get" meta-word-exists static_assert
  "ct-get-pattern-macro-group" meta-word-exists static_assert
  "meta-macro-pattern-group-set" meta-word-exists static_assert
  "ct-set-pattern-macro-group" meta-word-exists static_assert
  "meta-macro-pattern-groups-active" meta-word-exists static_assert
  "ct-list-active-pattern-groups" meta-word-exists static_assert
  "meta-macro-pattern-list" meta-word-exists static_assert
  "ct-list-pattern-macros" meta-word-exists static_assert
  "meta-macro-pattern-priority-get" meta-word-exists static_assert
  "ct-get-pattern-macro-priority" meta-word-exists static_assert
  "meta-macro-pattern-priority-set" meta-word-exists static_assert
  "ct-set-pattern-macro-priority" meta-word-exists static_assert
  "meta-macro-pattern-register" meta-word-exists static_assert
  "ct-register-pattern-macro" meta-word-exists static_assert
  "meta-macro-pattern-scope-active-set" meta-word-exists static_assert
  "ct-set-pattern-scope-active" meta-word-exists static_assert
  "meta-macro-pattern-scope-get" meta-word-exists static_assert
  "ct-get-pattern-macro-scope" meta-word-exists static_assert
  "meta-macro-pattern-scope-set" meta-word-exists static_assert
  "ct-set-pattern-macro-scope" meta-word-exists static_assert
  "meta-macro-pattern-scopes-active" meta-word-exists static_assert
  "ct-list-active-pattern-scopes" meta-word-exists static_assert
  "meta-macro-pattern-unregister" meta-word-exists static_assert
  "ct-unregister-pattern-macro" meta-word-exists static_assert
  "meta-macro-preview-get" meta-word-exists static_assert
  "ct-get-macro-preview" meta-word-exists static_assert
  "meta-macro-preview-set" meta-word-exists static_assert
  "ct-set-macro-preview" meta-word-exists static_assert
  "meta-macro-register" meta-word-exists static_assert
  "ct-register-text-macro" meta-word-exists static_assert
  "meta-macro-register-signature" meta-word-exists static_assert
  "ct-register-text-macro-signature" meta-word-exists static_assert
  "meta-macro-rename" meta-word-exists static_assert
  "ct-rename-macro" meta-word-exists static_assert
  "meta-macro-signature" meta-word-exists static_assert
  "ct-get-macro-signature" meta-word-exists static_assert
  "meta-macro-template-mode" meta-word-exists static_assert
  "ct-get-macro-template-mode" meta-word-exists static_assert
  "meta-macro-template-program-size" meta-word-exists static_assert
  "ct-get-macro-template-program-size" meta-word-exists static_assert
  "meta-macro-template-version" meta-word-exists static_assert
  "ct-get-macro-template-version" meta-word-exists static_assert
  "meta-parser-pos" meta-word-exists static_assert
  "ct-parser-pos" meta-word-exists static_assert
  "meta-parser-remaining" meta-word-exists static_assert
  "ct-parser-remaining" meta-word-exists static_assert
  "meta-reader-add" meta-word-exists static_assert
  "ct-add-reader-rewrite" meta-word-exists static_assert
  "meta-reader-add-named" meta-word-exists static_assert
  "ct-add-reader-rewrite-named" meta-word-exists static_assert
  "meta-reader-add-priority" meta-word-exists static_assert
  "ct-add-reader-rewrite-priority" meta-word-exists static_assert
  "meta-reader-clear" meta-word-exists static_assert
  "ct-clear-reader-rewrites" meta-word-exists static_assert
  "meta-reader-enabled-get" meta-word-exists static_assert
  "ct-get-reader-rewrite-enabled" meta-word-exists static_assert
  "meta-reader-enabled-set" meta-word-exists static_assert
  "ct-set-reader-rewrite-enabled" meta-word-exists static_assert
  "meta-reader-list" meta-word-exists static_assert
  "ct-list-reader-rewrites" meta-word-exists static_assert
  "meta-reader-priority-get" meta-word-exists static_assert
  "ct-get-reader-rewrite-priority" meta-word-exists static_assert
  "meta-reader-priority-set" meta-word-exists static_assert
  "ct-set-reader-rewrite-priority" meta-word-exists static_assert
  "meta-reader-remove" meta-word-exists static_assert
  "ct-remove-reader-rewrite" meta-word-exists static_assert
  "meta-rewrite-compatibility" meta-word-exists static_assert
  "ct-rewrite-compatibility-matrix" meta-word-exists static_assert
  "meta-rewrite-dry-run" meta-word-exists static_assert
  "ct-rewrite-dry-run" meta-word-exists static_assert
  "meta-rewrite-fixture" meta-word-exists static_assert
  "ct-rewrite-generate-fixture" meta-word-exists static_assert
  "meta-rewrite-index-rebuild" meta-word-exists static_assert
  "ct-rebuild-rewrite-index" meta-word-exists static_assert
  "meta-rewrite-index-stats" meta-word-exists static_assert
  "ct-get-rewrite-index-stats" meta-word-exists static_assert
  "meta-rewrite-loop-detect-get" meta-word-exists static_assert
  "ct-get-rewrite-loop-detection" meta-word-exists static_assert
  "meta-rewrite-loop-detect-set" meta-word-exists static_assert
  "ct-set-rewrite-loop-detection" meta-word-exists static_assert
  "meta-rewrite-loop-reports" meta-word-exists static_assert
  "ct-get-rewrite-loop-reports" meta-word-exists static_assert
  "meta-rewrite-loop-reports-clear" meta-word-exists static_assert
  "ct-clear-rewrite-loop-reports" meta-word-exists static_assert
  "meta-rewrite-max-steps-get" meta-word-exists static_assert
  "ct-get-rewrite-max-steps" meta-word-exists static_assert
  "meta-rewrite-max-steps-set" meta-word-exists static_assert
  "ct-set-rewrite-max-steps" meta-word-exists static_assert
  "meta-rewrite-pack-export" meta-word-exists static_assert
  "ct-export-rewrite-pack" meta-word-exists static_assert
  "meta-rewrite-pack-import" meta-word-exists static_assert
  "ct-import-rewrite-pack" meta-word-exists static_assert
  "meta-rewrite-pack-import-replace" meta-word-exists static_assert
  "ct-import-rewrite-pack-replace" meta-word-exists static_assert
  "meta-rewrite-pipeline-active-set" meta-word-exists static_assert
  "ct-set-rewrite-pipeline-active" meta-word-exists static_assert
  "meta-rewrite-pipeline-get" meta-word-exists static_assert
  "ct-get-rewrite-pipeline" meta-word-exists static_assert
  "meta-rewrite-pipeline-set" meta-word-exists static_assert
  "ct-set-rewrite-pipeline" meta-word-exists static_assert
  "meta-rewrite-pipelines-active" meta-word-exists static_assert
  "ct-list-rewrite-active-pipelines" meta-word-exists static_assert
  "meta-rewrite-profile-clear" meta-word-exists static_assert
  "ct-clear-rewrite-profile" meta-word-exists static_assert
  "meta-rewrite-profile-get" meta-word-exists static_assert
  "ct-get-rewrite-profile" meta-word-exists static_assert
  "meta-rewrite-provenance" meta-word-exists static_assert
  "ct-get-rewrite-provenance" meta-word-exists static_assert
  "meta-rewrite-saturation-get" meta-word-exists static_assert
  "ct-get-rewrite-saturation" meta-word-exists static_assert
  "meta-rewrite-saturation-set" meta-word-exists static_assert
  "ct-set-rewrite-saturation" meta-word-exists static_assert
  "meta-rewrite-specificity" meta-word-exists static_assert
  "ct-get-rewrite-specificity" meta-word-exists static_assert
  "meta-rewrite-trace-clear" meta-word-exists static_assert
  "ct-clear-rewrite-trace-log" meta-word-exists static_assert
  "meta-rewrite-trace-get" meta-word-exists static_assert
  "ct-get-rewrite-trace" meta-word-exists static_assert
  "meta-rewrite-trace-log" meta-word-exists static_assert
  "ct-get-rewrite-trace-log" meta-word-exists static_assert
  "meta-rewrite-trace-set" meta-word-exists static_assert
  "ct-set-rewrite-trace" meta-word-exists static_assert
  "meta-rewrite-txn-begin" meta-word-exists static_assert
  "ct-rewrite-txn-begin" meta-word-exists static_assert
  "meta-rewrite-txn-commit" meta-word-exists static_assert
  "ct-rewrite-txn-commit" meta-word-exists static_assert
  "meta-rewrite-txn-rollback" meta-word-exists static_assert
  "ct-rewrite-txn-rollback" meta-word-exists static_assert
  "meta-word-asm" meta-word-exists static_assert
  "ct-get-word-asm" meta-word-exists static_assert
  "meta-word-body" meta-word-exists static_assert
  "ct-get-word-body" meta-word-exists static_assert
  "meta-word-exists" meta-word-exists static_assert
  "ct-word-exists?" meta-word-exists static_assert
  "meta-word-list" meta-word-exists static_assert
  "ct-list-words" meta-word-exists static_assert
  "meta-word-list-prefix" meta-word-exists static_assert
  "ct-list-words-prefix" meta-word-exists static_assert
  "meta-word-remove" meta-word-exists static_assert
  "ct-unregister-word" meta-word-exists static_assert
end
compile-time verify_meta_ct_wrapper_coverage

word main
  1 puti cr
end
